#!/bin/sh
# Package every Rounds Codex asset pack. Generated by scripts/build_asset_pack_manifests.js.
#
# Run from the ROOT OF THE SITE TREE -- fileSelectors are relative paths from where this runs,
# so running it from anywhere else silently produces packs that are missing every file.
#
# On macOS with Xcode:   BA="xcrun ba-package"
# On Linux/Windows:      BA="ba-package"   (Managed Background Assets Developer Tools)
set -e
: "${BA:=xcrun ba-package}"
: "${MANIFESTS:=/home/user/rounds-codex/native/manifests}"
: "${OUTDIR:=./asset-packs}"
mkdir -p "$OUTDIR"

echo "==> rc-cardiac  (156 files, 148.2 MB)"
$BA create --manifest "$MANIFESTS/rc-cardiac.json" --output "$OUTDIR/rc-cardiac.aar"
echo "==> rc-endocrine  (151 files, 104.9 MB)"
$BA create --manifest "$MANIFESTS/rc-endocrine.json" --output "$OUTDIR/rc-endocrine.aar"
echo "==> rc-respiratory  (120 files, 92.0 MB)"
$BA create --manifest "$MANIFESTS/rc-respiratory.json" --output "$OUTDIR/rc-respiratory.aar"
echo "==> rc-gastrointestinal  (132 files, 84.7 MB)"
$BA create --manifest "$MANIFESTS/rc-gastrointestinal.json" --output "$OUTDIR/rc-gastrointestinal.aar"
echo "==> rc-neurology  (132 files, 69.9 MB)"
$BA create --manifest "$MANIFESTS/rc-neurology.json" --output "$OUTDIR/rc-neurology.aar"
echo "==> rc-msk-and-rheum  (99 files, 49.4 MB)"
$BA create --manifest "$MANIFESTS/rc-msk-and-rheum.json" --output "$OUTDIR/rc-msk-and-rheum.aar"
echo "==> rc-renal-and-gu  (77 files, 43.6 MB)"
$BA create --manifest "$MANIFESTS/rc-renal-and-gu.json" --output "$OUTDIR/rc-renal-and-gu.aar"
echo "==> rc-heme-and-onc  (77 files, 41.5 MB)"
$BA create --manifest "$MANIFESTS/rc-heme-and-onc.json" --output "$OUTDIR/rc-heme-and-onc.aar"
echo "==> rc-psychiatry  (77 files, 39.1 MB)"
$BA create --manifest "$MANIFESTS/rc-psychiatry.json" --output "$OUTDIR/rc-psychiatry.aar"
echo "==> rc-infectious-disease  (66 files, 35.4 MB)"
$BA create --manifest "$MANIFESTS/rc-infectious-disease.json" --output "$OUTDIR/rc-infectious-disease.aar"
echo "==> rc-ob-and-peds  (66 files, 33.3 MB)"
$BA create --manifest "$MANIFESTS/rc-ob-and-peds.json" --output "$OUTDIR/rc-ob-and-peds.aar"

echo "done: $(ls -1 "$OUTDIR" | wc -l) pack(s) in $OUTDIR"
