/* ===== Rounds Codex Rx — drug dataset (Phase 1: 50 drugs) =====
   Sources: FDA labels (DailyMed), Drugs.com, MedlinePlus. Verified per drug.
   cat = home specialty (one of the app's 21); cond = condition ids it maps to. */
const RX_DATA = [
{id:"atorvastatin",generic:"Atorvastatin",trade:["Lipitor"],cat:"Cardiac",cls:"HMG-CoA reductase inhibitor (statin)",sched:null,ver:true,cond:["hyperlipidemia","acs","pad","stroke","tia"],
 boxed:[],
 uses:["High LDL cholesterol (hyperlipidemia)","Prevention of MI and stroke (primary & secondary)","Familial hypercholesterolemia","CV risk reduction in type 2 diabetes"],
 dA:["Start 10–20 mg PO once daily, any time of day","Usual range 10–80 mg once daily","High-intensity (post-ACS, high risk): 40–80 mg daily","With strong CYP3A4 inhibitors: cap at 20 mg/day"],
 dP:["Heterozygous familial hypercholesterolemia, age 10–17: 10 mg once daily; range 10–20 mg"],
 dur:"Long-term, usually lifelong. Keep taking even when feeling well.",hl:"~14 h (effect lasts 20–30 h via active metabolites)",
 se:["Muscle pain/myopathy — rarely rhabdomyolysis with kidney injury","Elevated liver enzymes / hepatotoxicity","New-onset hyperglycemia / diabetes risk","Immune-mediated necrotizing myopathy (rare)"],
 ix:["Strong CYP3A4 inhibitors (clarithromycin, itraconazole, ritonavir) — ↑levels, myopathy; cap 20 mg","Cyclosporine — greatly ↑exposure; avoid","Gemfibrozil — high rhabdo risk; avoid","Grapefruit juice (large amounts) — ↑levels"],
 preg:"Generally avoided in pregnancy — stop when pregnancy is recognized. Not recommended while breastfeeding.",
 pills:[{f:"tablet",s:"10 mg",sh:"oval",c:"white",im:"PD 155",sc:false},{f:"tablet",s:"20 mg",sh:"oval",c:"white",im:"ATV20",sc:false},{f:"tablet",s:"40 mg",sh:"oval",c:"white",im:"ATV40",sc:false}],
 src:["https://www.drugs.com/atorvastatin.html","https://medlineplus.gov/druginfo/meds/a600045.html"]},

{id:"lisinopril",generic:"Lisinopril",trade:["Prinivil","Zestril"],cat:"Cardiac",cls:"ACE inhibitor",sched:null,ver:true,cond:["chf","htn","acs","ckd","t2dm"],
 boxed:["Fetal toxicity: can injure or kill the fetus in the 2nd/3rd trimester — stop as soon as pregnancy is detected."],
 uses:["Hypertension (adults & children ≥6 yr)","Heart failure (adjunct)","Survival after acute MI","Diabetic nephropathy / kidney protection"],
 dA:["HTN: start 10 mg PO once daily (5 mg if on a diuretic); usual 20–40 mg; max 80 mg/day","Heart failure: start 2.5–5 mg daily; titrate to max 40 mg","Acute MI: 5 mg within 24 h, then 5 mg at 24 h, 10 mg at 48 h, then 10 mg daily"],
 dP:["HTN, age ≥6: start 0.07 mg/kg once daily (max 5 mg); not for GFR <30"],
 dur:"Usually long-term/lifelong; ≥6 weeks after MI, often indefinitely.",hl:"12 h",
 se:["Angioedema (face/lip/tongue/airway swelling — can be fatal)","Hyperkalemia","Hypotension, dizziness, syncope","Acute kidney injury / rising creatinine","Dry persistent cough"],
 ix:["K+ supplements / K-sparing diuretics (spironolactone) — hyperkalemia","Sacubitril/valsartan — contraindicated; angioedema (36-h washout)","Lithium — ↑levels & toxicity","NSAIDs — ↓effect & kidney injury","Aliskiren — avoid dual RAS blockade"],
 preg:"Contraindicated in pregnancy (boxed warning) — fetal renal failure, oligohydramnios, death. Not recommended while breastfeeding.",
 pills:[{f:"tablet",s:"10 mg",sh:"round",c:"pink",im:"LUPIN 10",sc:false},{f:"tablet",s:"20 mg",sh:"round",c:"pink",im:"LUPIN 20",sc:false},{f:"tablet",s:"40 mg",sh:"round",c:"yellow",im:"LUPIN 40",sc:false}],
 src:["https://www.drugs.com/lisinopril.html","https://www.drugs.com/dosage/lisinopril.html"]},

{id:"losartan",generic:"Losartan",trade:["Cozaar"],cat:"Cardiac",cls:"Angiotensin II receptor blocker (ARB)",sched:null,ver:true,cond:["htn","chf","ckd"],
 boxed:["Fetal toxicity — can injure or kill the fetus; stop as soon as pregnancy is detected."],
 uses:["Hypertension (adults & children ≥6 yr)","Stroke risk reduction in HTN with LVH","Diabetic nephropathy in type 2 diabetes","HF alternative when ACE inhibitors not tolerated"],
 dA:["HTN: 50 mg PO once daily; range 25–100 mg/day in 1–2 doses","Start 25 mg if volume-depleted or hepatic impairment","Diabetic nephropathy: 50 mg once daily, up to 100 mg","Full effect may take 3–6 weeks"],
 dP:["HTN, age ≥6: 0.7 mg/kg once daily (max 50 mg); not for GFR <30"],
 dur:"Long-term, usually lifelong.",hl:"~2 h (active metabolite 6–9 h)",
 se:["Hyperkalemia","Dizziness / hypotension","Renal impairment (rising creatinine)","Angioedema (rare)","Fetal toxicity in pregnancy"],
 ix:["K+ supplements / K-sparing diuretics — hyperkalemia","Lithium — ↑levels & toxicity","NSAIDs — blunted BP effect, renal risk","Aliskiren — contraindicated in diabetes","Dual RAS blockade (ACEi/other ARB) — hypotension, hyperkalemia"],
 preg:"Contraindicated in pregnancy (boxed warning). Breastfeeding generally not recommended.",
 pills:[{f:"tablet",s:"25 mg",sh:"oval",c:"white",im:"ML 14",sc:false},{f:"tablet",s:"50 mg",sh:"oval",c:"white",im:"ML 15",sc:true},{f:"tablet",s:"100 mg",sh:"oval",c:"white",im:"ML 16",sc:false}],
 src:["https://www.drugs.com/losartan.html","https://medlineplus.gov/druginfo/meds/a695008.html"]},

{id:"amlodipine",generic:"Amlodipine",trade:["Norvasc"],cat:"Cardiac",cls:"Dihydropyridine calcium channel blocker",sched:null,ver:true,cond:["htn","acs"],
 boxed:[],
 uses:["Hypertension (adults & children ≥6 yr)","Chronic stable angina","Vasospastic (Prinzmetal) angina","Coronary artery disease"],
 dA:["HTN: 5 mg PO once daily; range 2.5–10 mg (max 10 mg/day)","Elderly/frail or hepatic impairment: start 2.5 mg","Angina/CAD: 5–10 mg once daily","Titrate every 7–14 days"],
 dP:["HTN, age 6–17: 2.5–5 mg once daily (max 5 mg/day)"],
 dur:"Long-term (often lifelong) daily therapy.",hl:"30–50 h",
 se:["Peripheral edema (ankle/leg swelling) — dose-related","Hypotension / dizziness","Flushing","Palpitations","Reflex tachycardia"],
 ix:["Strong CYP3A4 inhibitors (clarithromycin, ketoconazole) — ↑levels","Simvastatin — cap at 20 mg/day (myopathy)","Cyclosporine / tacrolimus — ↑levels, monitor","Other antihypertensives / nitrates — additive hypotension"],
 preg:"Limited data; crosses placenta. Use only if benefit outweighs risk. Small amounts in breast milk, no adverse effects reported.",
 pills:[{f:"tablet",s:"2.5 mg",sh:"diamond",c:"white",im:"2.5",sc:false},{f:"tablet",s:"5 mg",sh:"round",c:"white",im:"IG 238",sc:false},{f:"tablet",s:"10 mg",sh:"round",c:"white",im:"IG 239",sc:false}],
 src:["https://www.drugs.com/amlodipine.html","https://medlineplus.gov/druginfo/meds/a692044.html"]},

{id:"metoprolol",generic:"Metoprolol",trade:["Lopressor (tartrate)","Toprol-XL (succinate)"],cat:"Cardiac",cls:"Beta-1 selective (cardioselective) beta-blocker",sched:null,ver:true,cond:["htn","afib","chf","acs"],
 boxed:["Do not stop abruptly — sudden discontinuation can trigger angina, MI, or arrhythmia. Taper over 1–2 weeks."],
 uses:["Hypertension","Angina","Heart failure with reduced EF (succinate ER)","Acute MI / post-MI survival (tartrate)","Rate control in atrial fibrillation"],
 dA:["HTN (tartrate IR): 100 mg/day in 1–2 doses; max 450 mg/day","HTN (succinate ER): 25–100 mg once daily; max 400 mg/day","Heart failure (succinate ER only): start 12.5–25 mg daily, double q2 weeks to target 200 mg","Acute MI (tartrate): 5 mg IV q2min ×3, then 50 mg PO q6h"],
 dP:["HTN, age ≥6 (succinate ER): 1 mg/kg once daily (max 50 mg); up to 2 mg/kg"],
 dur:"Usually long-term/indefinite. Never stop abruptly — taper over 1–2 weeks.",hl:"3–7 h (longer in CYP2D6 poor metabolizers)",
 se:["Bradycardia & heart block","Hypotension, dizziness, fainting","Fatigue & depression","Worsening heart failure during up-titration","Bronchospasm at higher doses","Masks hypoglycemia symptoms"],
 ix:["CYP2D6 inhibitors (fluoxetine, paroxetine, bupropion) — ↑levels, bradycardia","Verapamil / diltiazem — additive AV block","Clonidine — rebound HTN if clonidine stopped; stop metoprolol first","Digoxin — additive AV slowing"],
 preg:"Use only if benefit justifies risk; may cause fetal/neonatal bradycardia & hypoglycemia. Generally compatible with breastfeeding (monitor infant).",
 pills:[{f:"tablet",s:"25 mg tartrate",sh:"round",c:"white",im:"M 18",sc:true},{f:"tablet",s:"50 mg tartrate",sh:"round",c:"pink",im:"M 32",sc:true},{f:"tablet ER",s:"25 mg succinate",sh:"oval",c:"white",im:"A ß",sc:true},{f:"tablet ER",s:"50 mg succinate",sh:"round",c:"white",im:"A mo",sc:true}],
 src:["https://www.drugs.com/metoprolol.html","https://medlineplus.gov/druginfo/meds/a682864.html"]},

{id:"furosemide",generic:"Furosemide",trade:["Lasix"],cat:"Cardiac",cls:"Loop diuretic",sched:null,ver:true,cond:["chf","fluid-overload","ckd","cirrhosis"],
 boxed:["Potent diuretic — excessive doses cause profound diuresis with water/electrolyte depletion; requires careful supervision."],
 uses:["Edema from heart failure","Edema from cirrhosis","Edema from kidney disease","Hypertension","Acute pulmonary edema (IV)"],
 dA:["Edema: 20–80 mg PO once daily; may ↑by 20–40 mg q6–8h; max 600 mg/day","HTN: 40 mg PO twice daily","Acute pulmonary edema: 40 mg IV over 1–2 min; may ↑to 80 mg IV","IV dose ≈ half the equivalent PO dose"],
 dP:["Edema: 2 mg/kg PO once; may ↑by 1–2 mg/kg q6–8h; IV 1 mg/kg/dose"],
 dur:"Often long-term for chronic HF/edema; short courses for acute overload.",hl:"~2 h",
 se:["Dehydration & hypotension","Hypokalemia (also ↓Na, Mg, Ca)","Ototoxicity / hearing loss (rapid high-dose IV)","Acute kidney injury","Hyperuricemia (gout flares)"],
 ix:["NSAIDs — blunt effect, kidney injury","Lithium — ↓clearance, toxicity","Aminoglycosides / cisplatin — additive oto/nephrotoxicity","Digoxin — hypokalemia ↑digoxin toxicity"],
 preg:"Use only if clearly needed. Passes into breast milk and may suppress lactation.",
 pills:[{f:"tablet",s:"20 mg",sh:"round",c:"white",im:"G164",sc:false},{f:"tablet",s:"40 mg",sh:"round",c:"white",im:"G 165",sc:true},{f:"tablet",s:"80 mg",sh:"round",c:"white",im:"G 166",sc:true}],
 src:["https://www.drugs.com/furosemide.html","https://www.drugs.com/pro/furosemide.html"]},

{id:"spironolactone",generic:"Spironolactone",trade:["Aldactone","CaroSpir"],cat:"Cardiac",cls:"Potassium-sparing diuretic (aldosterone antagonist)",sched:null,ver:true,cond:["chf","cirrhosis","htn"],
 boxed:[],
 uses:["Heart failure (NYHA III–IV, reduced EF)","Hypertension (add-on)","Edema/ascites from cirrhosis","Primary hyperaldosteronism","Acne & hirsutism (anti-androgen)"],
 dA:["Heart failure: 25 mg PO once daily; up to 50 mg","HTN: 25–100 mg/day in 1–2 doses","Edema (cirrhosis): 100 mg/day (range 25–200 mg)","Reduce frequency if eGFR 30–50"],
 dP:["Off-label: 1–3.3 mg/kg/day divided 1–2×"],
 dur:"Usually long-term chronic therapy.",hl:"~1.4 h (active metabolites 13–24 h)",
 se:["Hyperkalemia (can be life-threatening)","Gynecomastia & breast tenderness","Menstrual irregularities / erectile dysfunction","Hypotension & dizziness","Worsening renal function"],
 ix:["ACE inhibitors / ARBs — severe hyperkalemia","K+ supplements / other K-sparing diuretics — hyperkalemia","Trimethoprim (incl. TMP-SMX) — hyperkalemia","NSAIDs — ↓effect, hyperkalemia, renal injury","Lithium — ↓clearance, toxicity"],
 preg:"Avoid — anti-androgen effects may feminize a male fetus. Active metabolite in breast milk considered clinically inconsequential.",
 pills:[{f:"tablet",s:"25 mg",sh:"round",c:"yellow",im:"1001",sc:false},{f:"tablet",s:"50 mg",sh:"oval",c:"orange",im:"1041",sc:true},{f:"tablet",s:"100 mg",sh:"round",c:"peach",im:"1031",sc:true}],
 src:["https://www.drugs.com/spironolactone.html","https://www.drugs.com/pro/aldactone.html"]},

{id:"warfarin",generic:"Warfarin",trade:["Coumadin","Jantoven"],cat:"Cardiac",cls:"Vitamin K antagonist anticoagulant",sched:null,ver:true,cond:["afib","dvt","pe"],
 boxed:["Bleeding risk — can cause major or fatal bleeding. Monitor INR regularly; watch for drug/diet/illness interactions."],
 uses:["Treatment & prevention of DVT and PE","Stroke prevention in atrial fibrillation","Mechanical heart valves","After MI to reduce recurrent events"],
 dA:["Initial: 2–5 mg PO once daily (lower in elderly/liver disease)","Maintenance: 2–10 mg once daily, adjusted to INR","Target INR 2.0–3.0 for VTE, AF, aortic mechanical valve","Target INR 2.5–3.5 for mitral mechanical valve"],
 dP:["No controlled pediatric studies; ~0.1 mg/kg/day start with frequent INR monitoring"],
 dur:"3–6 months for a provoked clot; often indefinite for AF, recurrent VTE, mechanical valves.",hl:"20–60 h (mean ~40 h)",
 se:["Major bleeding (GI, intracranial)","Easy bruising, nosebleeds, hematuria","Skin necrosis (early, protein C deficiency)","Purple toe syndrome","Calciphylaxis (rare)"],
 ix:["NSAIDs / aspirin / antiplatelets — ↑bleeding","Many antibiotics & azoles (TMP-SMX, metronidazole, fluconazole) — ↑INR","Amiodarone — ↑INR","Rifampin, carbamazepine — ↓effect, clot risk","Vitamin K–rich foods — ↓effect"],
 preg:"Contraindicated in pregnancy (embryopathy, fetal bleeding), except some mechanical-valve patients. Compatible with breastfeeding.",
 pills:[{f:"tablet",s:"1 mg",sh:"oval",c:"pink",im:"1",sc:true},{f:"tablet",s:"2 mg",sh:"oval",c:"lavender",im:"2",sc:true},{f:"tablet",s:"2.5 mg",sh:"oval",c:"green",im:"2½",sc:true},{f:"tablet",s:"5 mg",sh:"oval",c:"peach",im:"5",sc:true},{f:"tablet",s:"10 mg",sh:"oval",c:"white",im:"10",sc:true}],
 src:["https://www.drugs.com/warfarin.html","https://www.drugs.com/pro/warfarin.html"]},

{id:"apixaban",generic:"Apixaban",trade:["Eliquis"],cat:"Cardiac",cls:"Direct factor Xa inhibitor (DOAC)",sched:null,ver:true,cond:["afib","dvt","pe"],
 boxed:["Stopping early (without alternative anticoagulation) ↑thrombotic events.","Spinal/epidural hematoma with neuraxial anesthesia — may cause permanent paralysis."],
 uses:["Stroke prevention in nonvalvular AF","Treatment of DVT and PE","Prevention of recurrent DVT/PE","VTE prophylaxis after hip/knee replacement"],
 dA:["Nonvalvular AF: 5 mg PO twice daily","Reduce to 2.5 mg BID if ≥2 of: age ≥80, ≤60 kg, creatinine ≥1.5","DVT/PE: 10 mg BID ×7 days, then 5 mg BID","Recurrent VTE prevention: 2.5 mg BID after ≥6 months"],
 dP:["Pediatric VTE (from birth, ≥2.6 kg): weight-tiered 0.3–10 mg BID after parenteral anticoagulation"],
 dur:"≥3–6 months for VTE; ongoing/indefinite for AF; 12–35 days after joint replacement.",hl:"~12 h",
 se:["Bleeding (GI, intracranial, wound)","Easy bruising","Heavy menstrual bleeding","Anemia","Hypersensitivity (rare)"],
 ix:["Strong dual CYP3A4+P-gp inhibitors (ketoconazole, ritonavir) — halve dose or avoid","Strong dual inducers (rifampin, carbamazepine, phenytoin) — ↓effect; avoid","Other anticoagulants — additive bleeding","Antiplatelets / NSAIDs / aspirin — ↑bleeding","SSRIs/SNRIs — ↑bleeding"],
 preg:"May cause maternal/fetal bleeding; not first-line. Breastfeeding not recommended.",
 pills:[{f:"tablet",s:"2.5 mg",sh:"round",c:"yellow",im:"893",sc:false},{f:"tablet",s:"5 mg",sh:"oval",c:"pink",im:"894",sc:false}],
 src:["https://www.drugs.com/apixaban.html","https://www.drugs.com/pro/eliquis.html"]},

{id:"heparin",generic:"Heparin (unfractionated)",trade:["Heparin Sodium"],cat:"Cardiac",cls:"Anticoagulant (activates antithrombin)",sched:null,ver:true,cond:["dvt","pe","acs"],
 boxed:[],
 uses:["Treatment of DVT and PE","Acute coronary syndromes (adjunct)","VTE prophylaxis in hospitalized/surgical patients","Anticoagulation for dialysis & procedures","Bridging (short half-life, reversible)"],
 dA:["VTE (weight-based drip): 80 units/kg IV bolus, then 18 units/kg/h, titrated to aPTT/anti-Xa","ACS: 60 units/kg bolus (max 4000), then 12 units/kg/h (max 1000/h)","SQ prophylaxis: 5000 units SQ q8–12h","Reversal: protamine sulfate"],
 dP:["Neonates/infants: 75–100 units/kg IV bolus, then 25–30 units/kg/h","Children: 75–100 units/kg bolus, then 18–20 units/kg/h (titrate)"],
 dur:"Short-term inpatient — usually days, until transitioned to oral anticoagulant or LMWH.",hl:"0.5–2 h (dose-dependent, ~60–90 min)",
 se:["Bleeding / hemorrhage","Heparin-induced thrombocytopenia (HIT) — immune platelet drop with paradoxical clotting; can occur weeks after stopping","Injection-site hematoma","Osteoporosis with prolonged use","Hyperkalemia (aldosterone suppression)"],
 ix:["Warfarin / other anticoagulants — additive bleeding (expected during overlap)","Antiplatelets (aspirin, clopidogrel, NSAIDs) — ↑bleeding","Thrombolytics — major hemorrhage risk","Nitroglycerin IV — possible heparin resistance"],
 preg:"Does not cross the placenta — preferred anticoagulant class in pregnancy (use preservative-free). Minimal transfer to breast milk.",
 pills:[{f:"vial",s:"1,000 units/mL"},{f:"vial",s:"5,000 units/mL"},{f:"vial",s:"10,000 units/mL"},{f:"vial",s:"25,000 units premix bag"}],
 src:["https://www.drugs.com/heparin.html","https://www.drugs.com/pro/heparin.html"]},

{id:"amiodarone",generic:"Amiodarone",trade:["Cordarone","Pacerone","Nexterone"],cat:"Cardiac",cls:"Class III antiarrhythmic",sched:null,ver:true,cond:["afib","cardiac-arrest","cardiomyopathy"],
 boxed:["Reserve for life-threatening arrhythmias; load in hospital.","Pulmonary toxicity (up to 17%; can be fatal).","Hepatotoxicity — can be severe/fatal.","Proarrhythmia — can worsen or provoke arrhythmias incl. torsades."],
 uses:["Life-threatening VF / unstable VT","Shock-refractory VF/pulseless VT (ACLS)","Atrial fibrillation rhythm control","Prevention of recurrent ventricular arrhythmias"],
 dA:["Cardiac arrest (VF/pulseless VT): 300 mg IV/IO push; may repeat 150 mg","VT with pulse: 150 mg IV over 10 min, then 1 mg/min ×6 h, then 0.5 mg/min ×18 h","Oral loading: 800–1600 mg/day ×1–3 weeks, then 600–800 mg/day ×1 month","Oral maintenance: usually 400 mg/day"],
 dP:["Cardiac arrest (PALS): 5 mg/kg IV/IO; may repeat (max 300 mg/dose). Not FDA-approved <18 yr."],
 dur:"Often long-term daily; IV typically 1–3 days bridged to oral.",hl:"~15–142 days (mean ~53 days); effects persist weeks–months",
 se:["Pulmonary fibrosis / pneumonitis","Hepatotoxicity","Thyroid dysfunction (hypo- or hyper-)","Bradycardia, AV block, hypotension (IV)","QT prolongation / torsades","Corneal microdeposits; blue-gray skin"],
 ix:["Warfarin — potentiated; cut warfarin dose ⅓–½","Digoxin — ↑levels; reduce dose","Beta-blockers / verapamil / diltiazem — bradycardia & AV block","Other QT-prolonging drugs — torsades","Simvastatin — myopathy/rhabdo"],
 preg:"Can cause fetal harm (neonatal bradycardia, hypothyroidism); avoid unless no alternative. Breastfeeding not recommended.",
 pills:[{f:"tablet",s:"200 mg",sh:"round",c:"pink",im:"200",sc:true},{f:"vial",s:"150 mg/3 mL"},{f:"vial",s:"premix 360 mg/200 mL"}],
 src:["https://www.drugs.com/pro/amiodarone.html","https://www.drugs.com/dosage/amiodarone.html"]},

{id:"norepinephrine",generic:"Norepinephrine",trade:["Levophed"],cat:"Emergency & Surgical",cls:"Vasopressor (α1 > β1 catecholamine)",sched:null,ver:true,cond:["shock","sepsis"],
 boxed:["Extravasation causes tissue ischemia/necrosis — infiltrate promptly with phentolamine."],
 uses:["Septic shock (first-line vasopressor)","Other distributive/vasodilatory shock","Severe hypotension unresponsive to fluids","Cardiogenic shock with hypotension (adjunct)"],
 dA:["Start 8–12 mcg/min IV (~0.05–0.1 mcg/kg/min); titrate to MAP ≥65","Usual maintenance 2–4 mcg/min; much higher often needed in refractory shock","Give via central line when possible; never IV push"],
 dP:["Shock (PALS, off-label): 0.05–0.1 mcg/kg/min IV, titrate (up to ~2 mcg/kg/min)"],
 dur:"Continuous infusion for hours to days; wean as shock resolves.",hl:"~2.4 min",
 se:["Tissue necrosis with extravasation","Peripheral / digital ischemia","Arrhythmias","Severe hypertension","Reflex bradycardia"],
 ix:["MAO inhibitors / linezolid — severe prolonged hypertension","Tricyclic antidepressants — exaggerated pressor response","Halogenated anesthetics — ventricular arrhythmias","Nonselective beta-blockers — unopposed alpha, severe HTN"],
 preg:"Do not withhold for life-threatening maternal hypotension. Breast-milk exposure unlikely clinically relevant.",
 pills:[{f:"vial",s:"4 mg/4 mL concentrate (dilute)"}],
 src:["https://www.drugs.com/pro/norepinephrine.html"]},

{id:"epinephrine",generic:"Epinephrine",trade:["Adrenalin","EpiPen"],cat:"Emergency & Surgical",cls:"Catecholamine (α- and β-agonist)",sched:null,ver:true,cond:["anaphylaxis","cardiac-arrest","shock"],
 boxed:[],
 uses:["Anaphylaxis (drug of choice)","Cardiac arrest (ACLS/PALS)","Hypotension / septic shock (infusion)","Severe asthma/bronchospasm","Symptomatic bradycardia unresponsive to atropine"],
 dA:["Anaphylaxis: 0.3–0.5 mg IM (1 mg/mL) in the thigh; repeat q5–10 min","Cardiac arrest: 1 mg IV/IO (0.1 mg/mL) q3–5 min","Shock: 0.05–2 mcg/kg/min IV, titrate to MAP","Severe asthma: 0.3–0.5 mg IM/SC"],
 dP:["Anaphylaxis: 0.01 mg/kg IM (max 0.3–0.5 mg), repeat q5–10 min","Cardiac arrest (PALS): 0.01 mg/kg IV/IO q3–5 min (max 1 mg)"],
 dur:"Single emergency doses; infusions run hours–days in shock.",hl:"<5 min (~2–3 min)",
 se:["Tachyarrhythmias / palpitations","Severe hypertension (stroke risk)","Myocardial ischemia / angina","Anxiety, tremor, headache","Pulmonary edema","Hyperglycemia, hypokalemia"],
 ix:["MAO inhibitors — dangerous potentiated pressor effect","Tricyclic antidepressants — exaggerated HTN/arrhythmias","Nonselective beta-blockers — severe HTN & blunted anaphylaxis response","Halogenated anesthetics — ventricular arrhythmias"],
 preg:"Use without hesitation in life-threatening maternal anaphylaxis/arrest. Compatible with breastfeeding.",
 pills:[{f:"vial",s:"1 mg/mL (IM)"},{f:"prefilled syringe",s:"0.1 mg/mL (IV/ACLS)"},{f:"auto-injector",s:"0.3 mg (EpiPen)"}],
 src:["https://www.drugs.com/dosage/epinephrine.html"]},

{id:"propofol",generic:"Propofol",trade:["Diprivan"],cat:"Emergency & Surgical",cls:"General anesthetic / sedative-hypnotic",sched:null,ver:true,cond:["seizure","icp","sci"],
 boxed:[],
 uses:["Induction & maintenance of general anesthesia","ICU sedation of intubated adults","Procedural (MAC) sedation","Refractory status epilepticus (off-label)"],
 dA:["Induction: 2–2.5 mg/kg IV (1–1.5 if elderly/debilitated)","ICU sedation: start 5 mcg/kg/min, titrate 5–50 mcg/kg/min (avoid >4 mg/kg/h — PRIS)","Procedural: 100–150 mcg/kg/min ×3–5 min, then 25–75 mcg/kg/min","Requires airway/hemodynamic monitoring"],
 dP:["Induction (≥3 yr): 2.5–3.5 mg/kg IV. NOT for pediatric ICU sedation (deaths reported)."],
 dur:"Single induction doses; ICU infusions hours–days. Discard opened vial/tubing within 12 h.",hl:"Clinical effect wears off in minutes (rapid redistribution)",
 se:["Hypotension","Respiratory depression & apnea","Bradycardia, asystole (rare)","Injection-site pain","Propofol infusion syndrome (acidosis, rhabdo, hyperK, cardiac failure)","Hypertriglyceridemia (prolonged)"],
 ix:["Opioids & benzodiazepines — additive sedation & cardiorespiratory depression","Valproate — ↑propofol levels; reduce dose","Antihypertensives / vasodilators — profound hypotension","Other CNS depressants (alcohol) — deeper sedation"],
 preg:"Crosses placenta; can cause neonatal sedation/respiratory depression. Small amounts in breast milk, no adverse effects reported.",
 pills:[{f:"emulsion vial",s:"10 mg/mL (white emulsion)"}],
 src:["https://www.drugs.com/pro/propofol.html"]},

{id:"ketamine",generic:"Ketamine",trade:["Ketalar"],cat:"Emergency & Surgical",cls:"Dissociative anesthetic (NMDA antagonist)",sched:"C-III",ver:true,cond:["shock","anaphylaxis"],
 boxed:[],
 uses:["Induction of anesthesia (esp. hemodynamic instability)","Procedural sedation & analgesia","RSI induction","Sub-dissociative analgesia (off-label)","Treatment-resistant depression (off-label)"],
 dA:["IV induction: 1–4.5 mg/kg slowly over ≥60 s (typical 1–2 mg/kg)","IM induction: 6.5–13 mg/kg","Maintenance: ½–full induction dose as needed","Analgesia: 0.1–0.3 mg/kg IV or low-dose infusion"],
 dP:["Label: safety not established <16 yr. Off-label procedural sedation: 1–2 mg/kg IV or 4–5 mg/kg IM."],
 dur:"Single doses / brief infusions; anesthesia ~5–10 min per IV dose, recovery 1–2 h.",hl:"~2.5 h",
 se:["Emergence reactions — hallucinations, vivid dreams, delirium","Hypertension & tachycardia","Laryngospasm","Increased salivation/secretions","↑Intracranial & intraocular pressure","Cystitis & dependence with chronic misuse"],
 ix:["Theophylline/aminophylline — lowers seizure threshold; avoid","Opioids & CNS depressants — profound sedation/respiratory depression","Sympathomimetics — exaggerated HTN/tachycardia","Benzodiazepines — prolong recovery (but blunt emergence)"],
 preg:"Not recommended in pregnancy/obstetrics — animal fetal neurotoxicity. Brief breastfeeding interruption after a dose is reasonable.",
 pills:[{f:"vial",s:"10, 50, 100 mg/mL"}],
 src:["https://www.drugs.com/pro/ketamine.html"]},

{id:"succinylcholine",generic:"Succinylcholine",trade:["Anectine","Quelicin"],cat:"Emergency & Surgical",cls:"Depolarizing neuromuscular blocker",sched:null,ver:true,cond:["shock"],
 boxed:["Pediatric risk: acute rhabdomyolysis with hyperkalemia, cardiac arrest, and death in children with undiagnosed myopathy (esp. boys ≤8 yr) — reserve pediatric use for emergency airway."],
 uses:["Paralysis for rapid sequence intubation (RSI)","Muscle relaxation for surgery","Facilitating mechanical ventilation","Muscle relaxation for ECT","Severe laryngospasm"],
 dA:["RSI: 1–1.5 mg/kg IV — paralysis in ~45–60 s","Short procedures: 0.3–1.1 mg/kg IV","No IV access: 3–4 mg/kg IM (max 150 mg)"],
 dP:["Emergency intubation only: infants/small children 2 mg/kg IV; older children 1 mg/kg IV"],
 dur:"Ultra-short: paralysis ~4–6 min after a single IV dose.",hl:"<1 min (hydrolyzed by pseudocholinesterase)",
 se:["Life-threatening hyperkalemia (burns, crush injury, denervation, myopathy)","Malignant hyperthermia trigger","Bradycardia & arrhythmias (esp. repeat doses/children)","Prolonged paralysis in pseudocholinesterase deficiency","↑Intraocular / intragastric pressure"],
 ix:["Volatile inhaled anesthetics — potentiate block & MH risk","Cholinesterase inhibitors — prolonged paralysis","Aminoglycosides — enhanced/prolonged block","Magnesium & lithium — enhanced block"],
 preg:"Decades of use without identified fetal risk; used at cesarean (minimal placental transfer). Low risk in lactation (rapid breakdown).",
 pills:[{f:"vial",s:"20 mg/mL injection"}],
 src:["https://www.drugs.com/monograph/succinylcholine-chloride.html"]},

{id:"rocuronium",generic:"Rocuronium",trade:["Zemuron"],cat:"Emergency & Surgical",cls:"Nondepolarizing (aminosteroid) neuromuscular blocker",sched:null,ver:true,cond:["shock"],
 boxed:["Paralyzing agent — causes respiratory arrest; fatal without ventilatory support. Trained personnel & airway equipment required."],
 uses:["Paralysis for RSI (non-depolarizing alternative to succinylcholine)","Muscle relaxation during surgery","Facilitating mechanical ventilation","Routine tracheal intubation"],
 dA:["RSI: 0.6–1.2 mg/kg IV (1.2 mg/kg fastest onset, ~60 s)","Standard intubation: 0.6 mg/kg IV (onset ~1 min, duration ~30 min)","Maintenance: 0.1–0.2 mg/kg IV as needed","Infusion: start 10–12 mcg/kg/min, titrate to twitch monitor"],
 dP:["Intubation: 0.45–0.6 mg/kg IV. Not recommended for RSI in children per label."],
 dur:"Intermediate: ~30 min at 0.6 mg/kg; 60+ min after 1.2 mg/kg. Reversible with sugammadex.",hl:"~1.4–1.5 h",
 se:["Respiratory arrest / residual postoperative paralysis","Anaphylaxis (rare but severe)","Transient hypertension / tachycardia","Prolonged block in hepatic disease","ICU myopathy (esp. with corticosteroids)"],
 ix:["Volatile inhaled anesthetics — potentiate & prolong block","Aminoglycosides — enhanced block","Magnesium & lithium — enhanced block","Chronic carbamazepine/phenytoin — resistance, shorter block","Sugammadex — rapidly reverses rocuronium"],
 preg:"Use only if benefit justifies risk; not recommended for RSI at cesarean. No human milk data.",
 pills:[{f:"vial",s:"10 mg/mL injection"}],
 src:["https://www.drugs.com/pro/rocuronium.html"]},

{id:"albuterol",generic:"Albuterol",trade:["ProAir HFA","Ventolin HFA","Proventil HFA"],cat:"Respiratory",cls:"Short-acting beta-2 agonist (SABA) bronchodilator",sched:null,ver:true,cond:["asthma","copd"],
 boxed:[],
 uses:["Quick relief of acute bronchospasm in asthma (rescue)","Bronchospasm relief in COPD","Prevention of exercise-induced bronchospasm","Nebulized treatment of acute exacerbations"],
 dA:["HFA inhaler (90 mcg/puff): 2 puffs q4–6h PRN","Exercise-induced: 2 puffs 15–30 min before exercise","Nebulizer: 2.5 mg q4–6h (may repeat q20 min ×3 in acute severe attacks)"],
 dP:["HFA (age ≥4): 2 puffs q4–6h PRN","Nebulizer (2–12 yr): 1.25–2.5 mg q4–6h"],
 dur:"Works in minutes; lasts ~4–6 h. Used as needed, not on a fixed schedule.",hl:"~6 h (adults); ~2.8 h in children 4–11",
 se:["Tremor & nervousness","Tachycardia & palpitations","Headache","Hypokalemia (high/repeated doses)","Paradoxical bronchospasm"],
 ix:["Beta-blockers — block bronchodilation, may trigger severe bronchospasm","MAO inhibitors / tricyclics — potentiate CV effects","Loop/thiazide diuretics — worsened hypokalemia","Digoxin — albuterol may lower levels"],
 preg:"Standard rescue agent, generally continued in pregnancy. Low systemic levels make breastfeeding acceptable.",
 pills:[{f:"inhaler",s:"HFA 90 mcg/puff"},{f:"nebule",s:"2.5 mg/3 mL solution"}],
 src:["https://www.drugs.com/pro/albuterol.html"]},

{id:"fluticasone-salmeterol",generic:"Fluticasone/Salmeterol",trade:["Advair Diskus","Advair HFA","Wixela"],cat:"Respiratory",cls:"Inhaled corticosteroid + long-acting beta-2 agonist (ICS/LABA)",sched:null,ver:true,cond:["asthma","copd"],
 boxed:[],
 uses:["Maintenance treatment of asthma (age 4+ Diskus)","Maintenance treatment of COPD","Reducing COPD exacerbations","NOT for acute bronchospasm"],
 dA:["Asthma (age ≥12): Diskus 100/50, 250/50, or 500/50 — 1 inhalation twice daily","Asthma HFA: 2 inhalations twice daily","COPD: Diskus 250/50 — 1 inhalation twice daily","Rinse mouth after use to prevent thrush"],
 dP:["Asthma, 4–11 yr: Diskus 100/50 — 1 inhalation twice daily"],
 dur:"Daily controller, twice daily; ~12 h per dose. Full effect over days–weeks.",hl:"Fluticasone ~11 h; salmeterol ~5.5 h",
 se:["Oral candidiasis (thrush)","Pneumonia (esp. COPD patients >65)","Dysphonia / hoarseness","Adrenal suppression & growth slowing in children (high doses)","LABA alone (without ICS) historically ↑asthma-death risk"],
 ix:["Strong CYP3A4 inhibitors (ritonavir, ketoconazole) — marked ↑exposure; avoid","MAO inhibitors / tricyclics — potentiated CV effects","Beta-blockers — block bronchodilation","Loop/thiazide diuretics — additive hypokalemia","Other LABAs — do not combine"],
 preg:"Weigh against the real harm of uncontrolled asthma. Expected low milk levels; generally compatible with breastfeeding.",
 pills:[{f:"inhaler",s:"Diskus 100/50, 250/50, 500/50 mcg"},{f:"inhaler",s:"HFA 45/21, 115/21, 230/21 mcg"}],
 src:["https://www.drugs.com/pro/advair-diskus.html"]},

{id:"montelukast",generic:"Montelukast",trade:["Singulair"],cat:"Respiratory",cls:"Leukotriene receptor antagonist",sched:null,ver:true,cond:["asthma"],
 boxed:["Serious neuropsychiatric events — agitation, depression, sleep disturbance, and suicidal thoughts/behavior. Reserve for allergic rhinitis only if other therapies fail."],
 uses:["Long-term asthma control (add-on)","Prevention of exercise-induced bronchoconstriction","Seasonal allergic rhinitis","Perennial allergic rhinitis"],
 dA:["Asthma or allergic rhinitis (age ≥15): 10 mg PO once daily (evening for asthma)","Exercise-induced: 10 mg at least 2 h before exercise; no repeat within 24 h"],
 dP:["6–14 yr: 5 mg chewable once daily (evening)","2–5 yr: 4 mg chewable or granules once daily","12–23 months (asthma): 4 mg granules once daily"],
 dur:"Ongoing daily controller (evening); not for an acute attack.",hl:"~2.7–5.5 h",
 se:["Neuropsychiatric events (agitation, aggression, depression, suicidality, vivid dreams)","Headache","Abdominal pain & diarrhea","Churg-Strauss / eosinophilic vasculitis (rare)","Hypersensitivity incl. angioedema"],
 ix:["Phenobarbital — ↓montelukast levels","Rifampin — ↓levels; monitor response","Gemfibrozil — ↑exposure several-fold","Phenytoin — reduced effect possible"],
 preg:"Registry/cohort data show no clear ↑in birth defects; often continued for asthma. Limited milk data — use caution.",
 pills:[{f:"tablet",s:"10 mg",sh:"square",c:"beige",im:"MSD 117",sc:false},{f:"chewable",s:"4 & 5 mg"}],
 src:["https://www.drugs.com/singulair.html"]},

{id:"metformin",generic:"Metformin",trade:["Glucophage","Glucophage XR"],cat:"Endocrine",cls:"Biguanide antihyperglycemic",sched:null,ver:true,cond:["t2dm"],
 boxed:["Lactic acidosis: rare but potentially fatal; risk ↑ with renal impairment (contraindicated eGFR <30), age >65, liver disease, hypoxia, heavy alcohol, iodinated contrast."],
 uses:["Type 2 diabetes (first-line)","Prediabetes (off-label)","PCOS (off-label)","Gestational diabetes (off-label)"],
 dA:["IR: 500 mg PO twice daily or 850 mg once daily with meals","Titrate by 500 mg weekly; usual 2000 mg/day; max 2550 mg/day","ER: 500–1000 mg once daily with evening meal; max 2000 mg/day","Do not start if eGFR 30–45; hold for iodinated contrast if risk factors"],
 dP:["Age ≥10 (IR): 500 mg PO twice daily; titrate weekly; max 2000 mg/day"],
 dur:"Long-term, often lifelong.",hl:"~6.2 h plasma (~17.6 h whole blood); prolonged in renal impairment",
 se:["Diarrhea, nausea, abdominal discomfort (common, usually transient)","Lactic acidosis (rare, life-threatening)","Vitamin B12 deficiency (long-term)","Metallic taste","Hypoglycemia (mainly with insulin/sulfonylureas)"],
 ix:["Iodinated contrast — hold metformin (AKI & lactic acidosis risk)","Alcohol (heavy/binge) — potentiates lactic acidosis","Topiramate / acetazolamide — ↑lactic acidosis risk","Cimetidine — ↑metformin levels","Insulin / sulfonylureas — additive hypoglycemia"],
 preg:"Widely used in pregnancy, though insulin often preferred. Small amounts in breast milk — discuss with provider.",
 pills:[{f:"tablet",s:"500 mg",sh:"round",c:"white",im:"500",sc:false},{f:"tablet",s:"1000 mg",sh:"oval",c:"white",im:"1000",sc:true},{f:"tablet ER",s:"500 mg",sh:"oblong",c:"white",im:"ER",sc:false}],
 src:["https://www.drugs.com/metformin.html","https://www.drugs.com/dosage/metformin.html"]},

{id:"semaglutide",generic:"Semaglutide",trade:["Ozempic","Wegovy","Rybelsus"],cat:"Endocrine",cls:"GLP-1 receptor agonist",sched:null,ver:true,cond:["t2dm"],
 boxed:["Thyroid C-cell tumor risk in rodents; human relevance unknown. Contraindicated with personal/family history of medullary thyroid carcinoma or MEN 2."],
 uses:["Type 2 diabetes (Ozempic, Rybelsus)","Chronic weight management (Wegovy)","CV risk reduction in T2DM / obesity with CVD","CKD risk reduction in T2DM (Ozempic)"],
 dA:["Ozempic (SC weekly): 0.25 mg ×4 wk → 0.5 mg → up to 1 mg → max 2 mg","Wegovy (SC weekly): escalate q4 wk to 2.4 mg maintenance","Rybelsus (PO daily): 3 mg ×30 days → 7 mg → max 14 mg, fasting with ≤4 oz water","0.25 mg start is for GI tolerability, not glucose control"],
 dP:["Wegovy: chronic weight management age 12+, titrate to 2.4 mg weekly. Ozempic/Rybelsus not approved in children."],
 dur:"Long-term; weight regain / glucose worsening common after stopping.",hl:"~1 week (persists ~5 weeks after last dose)",
 se:["Nausea, vomiting, diarrhea, constipation (common, dose-related)","Pancreatitis","Gallbladder disease","Acute kidney injury (often from dehydration)","Hypoglycemia with insulin/sulfonylureas","Diabetic retinopathy worsening (Ozempic)"],
 ix:["Insulin — ↑hypoglycemia; reduce insulin dose","Sulfonylureas — ↑hypoglycemia","Oral drugs — delayed gastric emptying may alter absorption (warfarin, levothyroxine)","Other GLP-1 agonists — do not combine"],
 preg:"Not recommended; stop ≥2 months before a planned pregnancy (long half-life). Avoid while breastfeeding.",
 pills:[{f:"pen",s:"Ozempic 0.25/0.5 mg"},{f:"pen",s:"Wegovy 2.4 mg"},{f:"tablet",s:"Rybelsus 7 mg",sh:"oval",c:"white",im:"7",sc:false}],
 src:["https://www.drugs.com/semaglutide.html","https://www.drugs.com/pro/ozempic.html"]},

{id:"insulin-glargine",generic:"Insulin glargine",trade:["Lantus","Basaglar","Toujeo"],cat:"Endocrine",cls:"Long-acting basal insulin analog",sched:null,ver:true,cond:["t1dm","t2dm","dka","hhs"],
 boxed:[],
 uses:["Basal insulin for type 1 diabetes (with mealtime insulin)","Basal insulin for type 2 diabetes","Once-daily glycemic control when orals insufficient"],
 dA:["T1DM: ~⅓ of total daily insulin SC once daily (total need ~0.4–1 units/kg/day); pair with rapid-acting","T2DM (insulin-naive): 0.2 units/kg (up to 10 units) SC once daily, then titrate to fasting glucose","Toujeo U-300: titrate no more often than q3–4 days","Give at the same time each day; never mix in a syringe"],
 dP:["Age ≥6 (T1DM): ~⅓ of total daily insulin (~0.2–0.4 units/kg/day initial)"],
 dur:"Daily long-term; lifelong in type 1 diabetes.",hl:"No pronounced peak; flat ~24 h profile (Toujeo up to 36 h)",
 se:["Hypoglycemia (most serious; can cause seizures/death)","Hypokalemia","Weight gain","Injection-site lipodystrophy (rotate sites)","Peripheral edema; HF when combined with TZDs"],
 ix:["Other antidiabetics & ACE inhibitors — additive hypoglycemia","Thiazolidinediones — fluid retention, HF risk","Beta-blockers, clonidine — mask hypoglycemia warning signs","Corticosteroids, thiazides, atypical antipsychotics — ↑glucose","Alcohol — unpredictable glucose effects"],
 preg:"Insulin is standard in pregnancy; no clear fetal-harm signal. Compatible with breastfeeding.",
 pills:[{f:"pen",s:"Lantus 100 units/mL"},{f:"pen",s:"Toujeo 300 units/mL"},{f:"vial",s:"100 units/mL"}],
 src:["https://www.drugs.com/insulin-glargine.html","https://www.drugs.com/pro/lantus.html"]},

{id:"insulin-lispro",generic:"Insulin lispro",trade:["Humalog","Admelog","Lyumjev"],cat:"Endocrine",cls:"Rapid-acting mealtime insulin analog",sched:null,ver:true,cond:["t1dm","t2dm","dka"],
 boxed:[],
 uses:["Mealtime (bolus) insulin for type 1 diabetes","Mealtime insulin in type 2 diabetes","Insulin pump (continuous SC infusion)","Correction dosing for hyperglycemia"],
 dA:["Inject SC within 15 min before or right after a meal","Typically 50–65% basal / remainder as lispro across meals","Total daily insulin commonly 0.4–1 units/kg/day (basal + bolus)","U-100 and U-200 pens deliver same units — do not convert"],
 dP:["Approved age 3+; individualized units/kg; often 0.4–1 units/kg/day (higher in puberty)"],
 dur:"Daily long-term with every meal; lifelong in type 1 diabetes.",hl:"~1 h SC; onset ~15 min, peak 30–90 min, lasts 2–4 h",
 se:["Hypoglycemia (most common; seizures/coma/death)","Hypokalemia","Weight gain","Injection-site lipodystrophy","Allergic reactions (rare anaphylaxis)"],
 ix:["Other hypoglycemics & ACE inhibitors — additive hypoglycemia","Thiazolidinediones — fluid retention, HF risk","Beta-blockers — mask hypoglycemia symptoms","Corticosteroids, thiazides, sympathomimetics — ↑glucose","Alcohol — unpredictable swings"],
 preg:"Insulin preferred in pregnancy; lispro widely used. Compatible with breastfeeding.",
 pills:[{f:"pen",s:"Humalog KwikPen 100 units/mL"},{f:"vial",s:"100 units/mL"}],
 src:["https://www.drugs.com/insulin-lispro.html","https://www.drugs.com/pro/humalog.html"]},

{id:"levothyroxine",generic:"Levothyroxine",trade:["Synthroid","Levoxyl","Tirosint"],cat:"Endocrine",cls:"Thyroid hormone (synthetic T4)",sched:null,ver:true,cond:["hypothyroid"],
 boxed:["Not for obesity/weight loss — ineffective and larger doses can cause serious or life-threatening toxicity, especially with sympathomimetic appetite suppressants."],
 uses:["Hypothyroidism (primary, secondary, tertiary)","TSH suppression in differentiated thyroid cancer","Myxedema coma (IV)","Post-thyroidectomy replacement"],
 dA:["~1.6 mcg/kg PO once daily on an empty stomach, 30–60 min before breakfast","Age >50 or cardiac disease: start 12.5–25 mcg; ↑q6–8 weeks","Recheck TSH q4–6 weeks until stable","Separate from interfering meds/food by ≥4 h"],
 dP:["0–3 mo: 10–15 mcg/kg/day; 1–5 yr: 5–6 mcg/kg/day; >12 yr (growth complete): ~1.6 mcg/kg/day","Congenital hypothyroidism: start promptly"],
 dur:"Usually lifelong replacement.",hl:"6–7 days (euthyroid); steady state ~4–6 weeks",
 se:["Over-replacement thyrotoxicosis: palpitations, tremor, heat intolerance, insomnia, weight loss","Atrial fibrillation, chest pain (elderly/cardiac)","↓Bone density with chronic overtreatment","Transient hair loss (first months)"],
 ix:["Calcium, iron, antacids, cholestyramine, sucralfate — block absorption; separate by 4 h","PPIs — reduced absorption","Warfarin — enhanced anticoagulant effect; monitor INR","Estrogens — may ↑levothyroxine requirement","Insulin/orals — may need dose adjustment"],
 preg:"Safe and essential in pregnancy — requirements often ↑, check TSH each trimester. Compatible with breastfeeding.",
 pills:[{f:"tablet",s:"50 mcg",sh:"round",c:"white",im:"50",sc:true},{f:"tablet",s:"75 mcg",sh:"round",c:"violet",im:"75",sc:true},{f:"tablet",s:"100 mcg",sh:"round",c:"yellow",im:"100",sc:true},{f:"tablet",s:"125 mcg",sh:"round",c:"brown",im:"125",sc:true},{f:"tablet",s:"150 mcg",sh:"round",c:"blue",im:"150",sc:true}],
 src:["https://www.drugs.com/levothyroxine.html","https://www.drugs.com/pro/synthroid.html"]},

{id:"prednisone",generic:"Prednisone",trade:["Deltasone","Rayos"],cat:"Endocrine",cls:"Corticosteroid (intermediate-acting glucocorticoid)",sched:null,ver:true,cond:["asthma","copd","ibd","ra","lupus"],
 boxed:[],
 uses:["Asthma/COPD exacerbations","Allergic reactions","Rheumatoid arthritis & lupus","Inflammatory bowel disease flares","Immune suppression (transplant, nephrotic syndrome)"],
 dA:["General anti-inflammatory: 5–60 mg PO daily, individualized","Asthma/COPD burst: 40–60 mg daily ×3–10 days (no taper for short courses)","Chronic disease: lowest effective dose; taper if used >~2 weeks"],
 dP:["Anti-inflammatory: 0.5–2 mg/kg/day","Asthma exacerbation: 1–2 mg/kg/day (max 60 mg) ×3–10 days"],
 dur:"Short bursts of 3–10 days for flares; weeks–months (with taper) for chronic disease.",hl:"Plasma ~2–3 h; biologic effect 18–36 h (once-daily dosing)",
 se:["Hyperglycemia","Insomnia & mood changes (psychosis at high doses)","Increased appetite & weight gain","Immunosuppression / infection risk","Adrenal suppression with abrupt stop","Osteoporosis & GI ulceration (long-term)"],
 ix:["NSAIDs / aspirin — additive GI ulcer/bleed","Live vaccines — avoid (disseminated infection, poor response)","Warfarin — altered INR; monitor","CYP3A4 inducers (rifampin, phenytoin) — ↓steroid effect","Insulin/orals — steroid raises glucose"],
 preg:"Use only if benefit justifies risk; largely inactivated by placenta. Compatible with breastfeeding at low–moderate doses.",
 pills:[{f:"tablet",s:"5 mg",sh:"round",c:"white",im:"5052",sc:true},{f:"tablet",s:"10 mg",sh:"round",c:"white",im:"5442",sc:true},{f:"tablet",s:"20 mg",sh:"round",c:"peach",im:"5443",sc:true}],
 src:["https://www.drugs.com/prednisone.html"]},

{id:"dexamethasone",generic:"Dexamethasone",trade:["Decadron","Hemady"],cat:"Endocrine",cls:"Corticosteroid (long-acting glucocorticoid)",sched:null,ver:true,cond:["croup","icp","brain-tumor","covid","cord-compression"],
 boxed:[],
 uses:["Croup","Cerebral edema (brain tumors)","Chemo-induced nausea/vomiting","Severe COVID-19 (hypoxic patients)","Airway swelling & severe allergic reactions"],
 dA:["Anti-inflammatory: 0.75–9 mg PO/IV/IM daily","Cerebral edema: 10 mg IV once, then 4 mg q6h; taper over 5–7 days","CINV: 12–20 mg before chemo, then 8 mg daily ×2–4 days","Taper if therapy lasts more than a few days"],
 dP:["Croup: 0.6 mg/kg PO/IM/IV ×1 (max 16 mg)","Cerebral edema: 0.2 mg/kg/24 h divided"],
 dur:"Often a single dose (croup) or a few days; longer courses need a taper.",hl:"Plasma ~4 h; biologic effect 36–72 h (longest-acting common steroid)",
 se:["Hyperglycemia","Insomnia, agitation, mood changes","Immunosuppression / infection risk","GI upset & ulceration","Adrenal suppression with abrupt stop","Fluid retention & hypertension"],
 ix:["NSAIDs / aspirin — additive GI bleed","Live vaccines — avoid","CYP3A4 inducers (rifampin, phenytoin) — ↓levels; dexamethasone also lowers levels of many drugs","Warfarin — altered INR","Insulin/orals — worsened glycemic control"],
 preg:"Crosses the placenta; use only if benefit justifies risk. Appears in breast milk — weigh risk vs benefit.",
 pills:[{f:"tablet",s:"4 mg",sh:"round",c:"green",im:"54 892",sc:true},{f:"vial",s:"4 mg/mL injection"}],
 src:["https://www.drugs.com/dexamethasone.html","https://www.drugs.com/pro/dexamethasone.html"]},

{id:"omeprazole",generic:"Omeprazole",trade:["Prilosec","Zegerid"],cat:"Gastrointestinal",cls:"Proton pump inhibitor (PPI)",sched:null,ver:true,cond:["gerd","pud","gi-bleed"],
 boxed:[],
 uses:["GERD & heartburn","Erosive esophagitis","Gastric & duodenal ulcers","H. pylori eradication (with antibiotics)","Zollinger-Ellison syndrome"],
 dA:["GERD: 20 mg PO once daily ×4 weeks (up to 8 for erosive esophagitis)","Duodenal ulcer: 20 mg daily ×4–8 weeks; H. pylori: 20 mg BID with antibiotics ×10–14 days","Take 30–60 min before a meal","OTC course is 14 days"],
 dP:["GERD (age 1–16): 10 to <20 kg: 10 mg daily; ≥20 kg: 20 mg daily"],
 dur:"Typically 4–8 weeks; long-term only for maintenance/hypersecretory states.",hl:"Plasma 0.5–1 h, but acid suppression up to 72 h (once-daily)",
 se:["Headache","Diarrhea, nausea, abdominal pain","Hypomagnesemia (long-term)","B12 deficiency (long-term)","↑Fracture risk (long-term)","C. difficile diarrhea","Acute interstitial nephritis (rare)"],
 ix:["Clopidogrel — avoid; omeprazole ↓its activation, ↓antiplatelet effect","Rilpivirine — contraindicated","High-dose methotrexate — ↑levels/toxicity","Acid-dependent drugs (ketoconazole, atazanavir, iron) — ↓absorption","Warfarin — ↑INR; monitor"],
 preg:"Human data do not show ↑birth-defect risk; acceptable when needed. May be present in breast milk — weigh benefit vs risk.",
 pills:[{f:"capsule",s:"20 mg DR",sh:"capsule",c:"purple/gray",im:"20",sc:false},{f:"capsule",s:"40 mg DR",sh:"capsule",c:"purple",im:"40",sc:false}],
 src:["https://www.drugs.com/omeprazole.html","https://www.drugs.com/pro/omeprazole.html"]},

{id:"pantoprazole",generic:"Pantoprazole",trade:["Protonix"],cat:"Gastrointestinal",cls:"Proton pump inhibitor (PPI)",sched:null,ver:true,cond:["gi-bleed","gerd","pud"],
 boxed:[],
 uses:["GERD with erosive esophagitis","Zollinger-Ellison & hypersecretory states","Upper GI bleed / stress ulcer prophylaxis (IV, common inpatient use)"],
 dA:["Erosive esophagitis: 40 mg PO once daily up to 8 weeks","Maintenance: 40 mg daily","Zollinger-Ellison: 40 mg BID, titrate (max 240 mg/day)","GI bleed (off-label): 80 mg IV bolus then infusion, or 40–80 mg IV"],
 dP:["Erosive esophagitis (age ≥5): 15–39 kg: 20 mg daily; ≥40 kg: 40 mg daily"],
 dur:"Usually up to 8 weeks for healing; ongoing for maintenance/hypersecretory states.",hl:"Plasma ~1 h; acid suppression ~24 h+ (once-daily)",
 se:["Headache","Diarrhea, nausea, abdominal pain","Hypomagnesemia (long-term)","↑Fracture risk (long-term)","C. difficile diarrhea","Acute interstitial nephritis (rare)"],
 ix:["Rilpivirine — contraindicated","High-dose methotrexate — ↑levels/toxicity","Acid-dependent drugs (ketoconazole, atazanavir, iron) — ↓absorption","Warfarin — possible ↑INR","Clopidogrel — preferred PPI (no important interaction, unlike omeprazole)"],
 preg:"No clear fetal-harm signal; acceptable when needed. Minimal milk transfer — generally compatible with breastfeeding.",
 pills:[{f:"tablet",s:"40 mg DR",sh:"oval",c:"yellow",im:"P9",sc:false},{f:"tablet",s:"20 mg DR",sh:"oval",c:"yellow",im:"P8",sc:false},{f:"vial",s:"40 mg injection"}],
 src:["https://www.drugs.com/pantoprazole.html","https://www.drugs.com/pro/pantoprazole.html"]},

{id:"ondansetron",generic:"Ondansetron",trade:["Zofran","Zofran ODT"],cat:"Gastrointestinal",cls:"5-HT3 receptor antagonist (antiemetic)",sched:null,ver:true,cond:["pancreatitis","bowel-obstruction","gi-bleed"],
 boxed:[],
 uses:["Chemotherapy-induced nausea/vomiting","Postoperative nausea/vomiting","Radiation-induced nausea/vomiting","Acute gastroenteritis vomiting (off-label, esp. peds)"],
 dA:["Highly emetogenic chemo: 24 mg PO once, 30 min before (or 0.15 mg/kg IV, max 16 mg/dose)","Moderately emetogenic chemo: 8 mg PO BID","Post-op: 4 mg IV/IM at induction, or 16 mg PO 1 h before anesthesia","Radiation: 8 mg PO TID"],
 dP:["Chemo, 4–11 yr: 4 mg PO TID","Chemo IV (6 mo–18 yr): 0.15 mg/kg (max 16 mg) at 0, 4, 8 h","Gastroenteritis (off-label): weight-based ODT (2 mg 8–15 kg; 4 mg 15–30 kg; 8 mg >30 kg)"],
 dur:"As needed around chemo, radiation, or surgery — a single dose to a few days.",hl:"~3–5 h (longer in elderly/hepatic impairment)",
 se:["Headache","Constipation or diarrhea","QT prolongation / torsades (dose-dependent)","Serotonin syndrome (with serotonergic drugs)","Drowsiness/fatigue"],
 ix:["Apomorphine — contraindicated (profound hypotension, LOC)","QT-prolonging drugs (antiarrhythmics, antipsychotics, methadone) — additive torsades","Serotonergic drugs (SSRIs, SNRIs, fentanyl) — serotonin syndrome","Tramadol — ↓analgesia + serotonin risk","CYP3A4 inducers (rifampin, phenytoin) — ↓levels"],
 preg:"Data inconsistent; small possible ↑in oral clefts — widely used when benefit outweighs risk. Milk transfer unknown.",
 pills:[{f:"tablet",s:"4 mg",sh:"oval",c:"white",im:"4",sc:false},{f:"tablet",s:"8 mg",sh:"oval",c:"yellow",im:"8",sc:false},{f:"ODT",s:"4 & 8 mg"}],
 src:["https://www.drugs.com/ondansetron.html","https://www.drugs.com/pro/ondansetron.html"]},

{id:"amoxicillin",generic:"Amoxicillin",trade:["Amoxil","Moxatag"],cat:"Infectious Disease",cls:"Aminopenicillin antibiotic",sched:null,ver:true,cond:["otitis-media","strep-pharyngitis","sinusitis","cap"],
 boxed:[],
 uses:["Otitis media","Strep throat (pharyngitis)","Sinusitis","Community-acquired pneumonia","Urinary tract infection","H. pylori (combination)"],
 dA:["Most infections: 500 mg PO q8h or 875 mg PO q12h","Strep throat: 1000 mg once daily (or 500 mg BID) ×10 days","Mild/UTI: 250 mg q8h or 500 mg q12h","H. pylori: 1 g q12h ×14 days with clarithromycin + PPI"],
 dP:["Otitis media: high-dose 80–90 mg/kg/day divided q12h","CAP: 90 mg/kg/day divided q12h (max 4 g/day)","Strep: 50 mg/kg once daily (max 1000 mg) ×10 days"],
 dur:"5–14 day courses typical; 10 days for strep, 14 for H. pylori.",hl:"~1 h (longer in renal impairment)",
 se:["Hypersensitivity / anaphylaxis (penicillin allergy)","Rash — very common if given during mononucleosis (avoid)","Diarrhea","C. difficile colitis","Severe skin reactions (rare, SJS)"],
 ix:["Allopurinol — ↑rash","Probenecid — ↓excretion, ↑levels","Warfarin — may ↑INR/bleeding","Oral contraceptives — possible ↓effectiveness","Methotrexate — ↓clearance, ↑toxicity"],
 preg:"Generally considered safe in pregnancy. Small amounts in breast milk — watch infant for rash/diarrhea.",
 pills:[{f:"capsule",s:"500 mg",sh:"capsule",c:"buff",im:"3109",sc:false},{f:"tablet",s:"875 mg",sh:"oval",c:"white",im:"875",sc:true}],
 src:["https://www.drugs.com/amoxicillin.html","https://www.drugs.com/dosage/amoxicillin.html"]},

{id:"ceftriaxone",generic:"Ceftriaxone",trade:["Rocephin"],cat:"Infectious Disease",cls:"Third-generation cephalosporin",sched:null,ver:true,cond:["cap","meningitis","uti","endocarditis"],
 boxed:[],
 uses:["Community-acquired pneumonia","Bacterial meningitis","Gonorrhea","Pyelonephritis / complicated UTI","Intra-abdominal infections","Sepsis (empiric)"],
 dA:["Most infections: 1–2 g IV/IM once daily (max 4 g/day)","Meningitis: 2 g IV q12h","Uncomplicated gonorrhea: 500 mg IM ×1 (1 g if ≥150 kg)"],
 dP:["General (≥1 mo): 50–75 mg/kg/day divided q12h (max 2 g/day)","Meningitis: 100 mg/kg load then 100 mg/kg/day (max 4 g/day)","Contraindicated in neonates ≤28 days with IV calcium (fatal precipitates), and in hyperbilirubinemic neonates"],
 dur:"4–14 day courses; single dose for gonorrhea.",hl:"5.8–8.7 h (once-daily dosing)",
 se:["Hypersensitivity (possible penicillin cross-reactivity)","Injection-site pain / phlebitis","Diarrhea & C. difficile colitis","Biliary sludging / pseudolithiasis","Hemolytic anemia (rare)"],
 ix:["IV calcium solutions (LR, TPN) — fatal ceftriaxone-calcium precipitates in neonates; never co-administer","Warfarin — ↑INR/bleeding","Aminoglycosides — do not mix in the same syringe","Live typhoid/BCG vaccines — ↓response"],
 preg:"No evidence of fetal harm. Low milk concentrations — use with caution while nursing.",
 pills:[{f:"vial",s:"250 mg / 500 mg / 1 g / 2 g"}],
 src:["https://www.drugs.com/ceftriaxone.html","https://www.drugs.com/pro/ceftriaxone.html"]},

{id:"azithromycin",generic:"Azithromycin",trade:["Zithromax","Z-Pak"],cat:"Infectious Disease",cls:"Macrolide antibiotic",sched:null,ver:true,cond:["cap","copd","strep-pharyngitis"],
 boxed:[],
 uses:["Community-acquired pneumonia (atypical coverage)","Strep throat (penicillin-allergic)","Chlamydia","Otitis media","COPD exacerbations / bronchitis","MAC prophylaxis in HIV"],
 dA:["Z-Pak: 500 mg PO day 1, then 250 mg daily days 2–5","Chlamydia: 1 g PO ×1","CAP (IV): 500 mg IV daily, transition to oral"],
 dP:["Otitis media (≥6 mo): 30 mg/kg ×1, or 10 mg/kg/day ×3 days","Pneumonia: 10 mg/kg day 1 (max 500), then 5 mg/kg days 2–5"],
 dur:"1–5 day courses (long tissue half-life extends effect); single dose for chlamydia.",hl:"~68 h (persists ~2 weeks after last dose)",
 se:["QT prolongation & torsades","Diarrhea","Nausea / abdominal pain","Severe (rarely fatal) hepatotoxicity","Severe skin reactions (SJS/DRESS, rare)","Infantile pyloric stenosis (neonates)"],
 ix:["QT-prolonging drugs (antiarrhythmics, antipsychotics, fluoroquinolones) — additive torsades","Warfarin — ↑INR/bleeding","Digoxin — ↑levels/toxicity","Aluminum/magnesium antacids — ↓peak levels; separate","Colchicine — ↑toxicity"],
 preg:"No ↑birth-defect signal. Passes into breast milk — monitor infant for diarrhea/vomiting/rash.",
 pills:[{f:"tablet",s:"250 mg",sh:"oval",c:"pink",im:"306",sc:false},{f:"tablet",s:"500 mg",sh:"oval",c:"pink",im:"500",sc:false}],
 src:["https://www.drugs.com/azithromycin.html","https://www.drugs.com/dosage/azithromycin.html"]},

{id:"doxycycline",generic:"Doxycycline",trade:["Vibramycin","Doryx","Oracea"],cat:"Infectious Disease",cls:"Tetracycline antibiotic",sched:null,ver:true,cond:["cap","cellulitis","acne"],
 boxed:[],
 uses:["Acne & rosacea","Community-acquired pneumonia (atypicals)","Chlamydia & other STIs","Tick-borne illness (Lyme, RMSF)","Skin/soft tissue incl. CA-MRSA","Malaria prophylaxis"],
 dA:["Most infections: 100 mg PO q12h day 1, then 100 mg daily","Chlamydia/Lyme: 100 mg BID (7 days chlamydia; 10–21 days Lyme)","Malaria prophylaxis: 100 mg daily, start 1–2 days before travel, continue 4 weeks after","Rosacea (Oracea): 40 mg once daily"],
 dP:[">8 yr or ≥45 kg: adult dosing","≤45 kg: 4.4 mg/kg/day divided q12h day 1, then 2.2 mg/kg","Avoid <8 yr except severe infection (e.g. RMSF) — tooth-staining risk"],
 dur:"7–14 day courses; weeks–months for acne; malaria prophylaxis continues 4 weeks after travel.",hl:"~16–22 h (unchanged in renal impairment)",
 se:["Photosensitivity (exaggerated sunburn)","Esophagitis / ulceration (take with fluids, stay upright)","Nausea / GI upset","Permanent tooth discoloration (fetus/children <8)","Intracranial hypertension (pseudotumor cerebri)","C. difficile colitis"],
 ix:["Antacids / iron / calcium / bismuth — chelation blocks absorption; separate by 2 h","Isotretinoin — additive intracranial hypertension; avoid","Warfarin — enhanced anticoagulant effect","Rifampin, carbamazepine, phenytoin — ↓doxycycline levels","Oral contraceptives — possible ↓effectiveness"],
 preg:"Avoid in pregnancy (fetal tooth discoloration, bone growth inhibition) and in children <8 except serious infection. Do not breastfeed while taking.",
 pills:[{f:"capsule",s:"100 mg",sh:"capsule",c:"blue",im:"095",sc:false}],
 src:["https://www.drugs.com/doxycycline.html","https://www.drugs.com/dosage/doxycycline.html"]},

{id:"vancomycin",generic:"Vancomycin",trade:["Vancocin","Firvanq"],cat:"Infectious Disease",cls:"Glycopeptide antibiotic",sched:null,ver:true,cond:["cdiff","cellulitis","endocarditis","meningitis","sepsis","osteomyelitis"],
 boxed:[],
 uses:["Serious MRSA infections (bacteremia, endocarditis, pneumonia, osteomyelitis)","Severe skin/soft tissue infections","Bacterial meningitis (with other agents)","C. difficile infection (oral only)","Empiric sepsis coverage"],
 dA:["IV: 15–20 mg/kg (actual body weight) q8–12h for serious infections","Loading dose (critically ill): 20–35 mg/kg IV once (max 3000 mg)","Monitor: target AUC24/MIC 400–600 (preferred) or trough 15–20 for serious MRSA","Oral C. diff: 125 mg PO q6h ×10 days (fulminant: 500 mg q6h). IV does NOT treat C. diff"],
 dP:["Serious MRSA (≥3 mo): 60–80 mg/kg/day IV divided q6–8h","Neonates: 15 mg/kg load, then 10 mg/kg q12h (week 1), q8h after","Monitor levels as in adults"],
 dur:"IV: 7–14 days typical, up to 4–6 weeks for bacteremia/endocarditis/bone; oral C. diff: 10 days.",hl:"4–6 h IV (markedly prolonged in renal impairment)",
 se:["Nephrotoxicity / acute kidney injury","Vancomycin infusion reaction ('red man') — flushing, hypotension with rapid infusion; give over ≥60 min","Ototoxicity — hearing loss, tinnitus","Thrombophlebitis at infusion site","Neutropenia (prolonged use)","DRESS (rare)"],
 ix:["Piperacillin-tazobactam — ↑acute kidney injury","Aminoglycosides — additive nephro/ototoxicity","Loop diuretics (furosemide) — ↑oto/nephrotoxicity","NSAIDs & IV contrast — additive kidney injury","Other nephrotoxins (amphotericin B, cisplatin) — enhanced toxicity"],
 preg:"No drug-associated birth-defect signal; use if clearly needed (monitor levels). Oral infant absorption minimal.",
 pills:[{f:"vial",s:"500 mg / 750 mg / 1 g"},{f:"capsule",s:"125 mg (oral, C. diff)"}],
 src:["https://www.drugs.com/vancomycin.html","https://www.drugs.com/dosage/vancomycin.html"]},

{id:"piperacillin-tazobactam",generic:"Piperacillin/Tazobactam",trade:["Zosyn"],cat:"Infectious Disease",cls:"Extended-spectrum penicillin + beta-lactamase inhibitor",sched:null,ver:true,cond:["sepsis","cap","febrile-neutropenia","diverticulitis"],
 boxed:[],
 uses:["Intra-abdominal infections","Hospital-acquired pneumonia","Skin & soft tissue infections","Gynecologic infections (PID, endometritis)","Empiric sepsis / febrile neutropenia coverage"],
 dA:["Most infections: 3.375 g IV q6h over 30 min","Nosocomial pneumonia / Pseudomonas: 4.5 g IV q6h (often with an aminoglycoside)","Extended infusion (common): 3.375–4.5 g over 4 h q8h","Reduce dose if CrCl <40"],
 dP:["2–9 mo: 90 mg/kg IV q8h",">9 mo & ≤40 kg: 112.5 mg/kg IV q8h",">40 kg: adult dosing"],
 dur:"Usually 4–10 days IV; up to 14 days for hospital-acquired pneumonia.",hl:"0.7–1.2 h",
 se:["Diarrhea (incl. C. difficile colitis)","Hypersensitivity / anaphylaxis (penicillin allergy)","Acute kidney injury","Cytopenias with prolonged use","Seizures at high doses in renal failure","Hypokalemia"],
 ix:["Vancomycin — ↑acute kidney injury; monitor renal function","Aminoglycosides — inactivated if mixed in same line; give separately","Probenecid — ↓clearance, ↑levels","Methotrexate — ↓clearance, ↑toxicity","Vecuronium — prolonged neuromuscular blockade"],
 preg:"Penicillins generally acceptable in pregnancy when needed. Excreted in breast milk — use with caution.",
 pills:[{f:"vial",s:"3.375 g / 4.5 g"}],
 src:["https://www.drugs.com/pro/zosyn.html","https://www.drugs.com/dosage/piperacillin-tazobactam.html"]},

{id:"metronidazole",generic:"Metronidazole",trade:["Flagyl"],cat:"Infectious Disease",cls:"Nitroimidazole antibiotic/antiprotozoal",sched:null,ver:true,cond:["cdiff","diverticulitis","pid"],
 boxed:["Carcinogenicity shown in mice and rats — reserve for approved indications, avoid unnecessary use."],
 uses:["Anaerobic bacterial infections (abdomen, pelvis, skin, CNS, bone)","Trichomoniasis","Bacterial vaginosis","Amebiasis","C. difficile infection (alternative agent)"],
 dA:["Anaerobic infections: 500 mg PO/IV q6–8h (max 4 g/day)","Trichomoniasis: 2 g PO ×1, or 500 mg BID ×7 days (treat partner)","Amebiasis: 500–750 mg PO TID ×5–10 days","Bacterial vaginosis: 500 mg PO BID ×7 days"],
 dP:["Amebiasis: 35–50 mg/kg/day divided TID ×10 days","Anaerobic infections: 7.5 mg/kg/dose q6–8h"],
 dur:"Usually 5–10 days; trichomoniasis can be a single 2 g dose.",hl:"~8 h",
 se:["Nausea & GI upset","Metallic taste","Headache","Peripheral neuropathy (prolonged use)","CNS toxicity — seizures, encephalopathy (rare)","Dark urine (harmless)"],
 ix:["Alcohol — disulfiram-like reaction (flushing, cramps, vomiting); avoid during and 3 days after","Warfarin — potentiates anticoagulation, ↑INR/bleeding","Disulfiram — psychotic reactions; avoid within 2 weeks","Lithium — ↑levels/toxicity","Phenytoin/phenobarbital — ↓metronidazole effect"],
 preg:"Contraindicated in the first trimester for trichomoniasis; otherwise use only if clearly needed. Consider pumping/discarding milk during and 48 h after therapy.",
 pills:[{f:"tablet",s:"500 mg",sh:"oblong",c:"white",im:"500",sc:false}],
 src:["https://www.drugs.com/metronidazole.html","https://www.drugs.com/pro/flagyl.html"]},

{id:"gabapentin",generic:"Gabapentin",trade:["Neurontin","Gralise"],cat:"Neurology",cls:"Gabapentinoid anticonvulsant / neuropathic pain agent",sched:null,ver:true,cond:["seizure","herpes-zoster"],
 boxed:[],
 uses:["Postherpetic neuralgia (shingles nerve pain)","Partial-onset seizures (adjunct, age 3+)","Neuropathic pain incl. diabetic neuropathy (off-label)","Restless legs syndrome (Horizant)"],
 dA:["Postherpetic neuralgia: 300 mg day 1, 300 mg BID day 2, 300 mg TID day 3; titrate to 1800 mg/day","Epilepsy (adjunct, age ≥12): start 300 mg TID; usual 900–1800 mg/day (up to 3600 mg used)","Reduce dose in renal impairment (renally cleared)","Take ≥2 h after antacids"],
 dP:["Epilepsy adjunct, 3–11 yr: start 10–15 mg/kg/day divided TID; maintenance 25–35 mg/kg/day"],
 dur:"Long-term maintenance for seizures/chronic nerve pain; taper over ≥1 week — do not stop abruptly.",hl:"5–7 h (prolonged in renal impairment)",
 se:["Dizziness","Somnolence / sedation","Peripheral edema","Ataxia / coordination problems","Respiratory depression (with opioids or lung disease)","Mood changes / suicidal thoughts","DRESS (rare, can be fatal)"],
 ix:["Opioids — life-threatening sedation & respiratory depression (morphine also ↑gabapentin levels)","Other CNS depressants (benzodiazepines, sleep aids) — additive sedation","Alcohol — ↑dizziness/drowsiness","Aluminum/magnesium antacids — ↓absorption; separate by 2 h"],
 preg:"Observational data have not shown ↑major defects, but animal developmental toxicity — use only if benefit outweighs risk. Secreted in breast milk; monitor infant for sedation.",
 pills:[{f:"capsule",s:"300 mg",sh:"capsule",c:"yellow",im:"215",sc:false},{f:"tablet",s:"600 mg",sh:"oval",c:"white",im:"600",sc:true}],
 src:["https://www.drugs.com/gabapentin.html","https://www.drugs.com/pro/gabapentin.html"]},

{id:"levetiracetam",generic:"Levetiracetam",trade:["Keppra","Keppra XR"],cat:"Neurology",cls:"Antiepileptic (SV2A modulator)",sched:null,ver:true,cond:["seizure"],
 boxed:[],
 uses:["Partial-onset (focal) seizures","Myoclonic seizures (juvenile myoclonic epilepsy, age 12+)","Primary generalized tonic-clonic seizures (age 6+)","Status epilepticus (off-label, second-line IV)"],
 dA:["Seizures: 500 mg PO/IV twice daily; ↑by 1000 mg/day q2 weeks to 3000 mg/day","Status epilepticus (guideline-based, off-label): 60 mg/kg IV load, max 4500 mg","Reduce dose in renal impairment"],
 dP:["1 to <6 mo: 7 mg/kg BID → max 21 mg/kg BID","6 mo to <4 yr: 10 mg/kg BID → 25 mg/kg BID","4 to <16 yr: 10 mg/kg BID → 30 mg/kg BID"],
 dur:"Long-term daily maintenance; do not stop abruptly — taper to avoid rebound seizures.",hl:"~7 h",
 se:["Somnolence / drowsiness","Fatigue / weakness","Dizziness","Behavioral changes — irritability, aggression, psychosis ('Keppra rage')","Mood changes & suicidal thoughts","Serious rash (SJS/DRESS, rare)"],
 ix:["Alcohol / CNS depressants — additive sedation","Enzyme-inducing antiepileptics (phenytoin, carbamazepine) — modestly ↑clearance in children","Notably few major interactions (no significant effect on warfarin, phenytoin, oral contraceptives)","Other sedating antiepileptics — additive somnolence"],
 preg:"No clear birth-defect signal, but levels fall in pregnancy (esp. 3rd trimester) — monitor closely. Excreted in breast milk; discuss risks/benefits.",
 pills:[{f:"tablet",s:"500 mg",sh:"oblong",c:"yellow",im:"500",sc:true},{f:"tablet",s:"750 mg",sh:"oblong",c:"orange",im:"750",sc:true}],
 src:["https://www.drugs.com/levetiracetam.html","https://www.drugs.com/pro/keppra.html"]},

{id:"naloxone",generic:"Naloxone",trade:["Narcan","Kloxxado","Zimhi"],cat:"Toxicology",cls:"Opioid antagonist (overdose reversal)",sched:null,ver:true,cond:["opioid-od"],
 boxed:[],
 uses:["Emergency reversal of opioid overdose","Reversal of postoperative opioid respiratory depression","Neonatal opioid-induced depression","Community / bystander overdose response (nasal spray)"],
 dA:["Overdose: 0.4–2 mg IV/IM/SubQ; repeat q2–3 min; question diagnosis if no response after 10 mg","Narcan nasal spray: 4 mg in one nostril; repeat q2–3 min (alternate nostrils) — call 911 first","Post-op depression: 0.1–0.2 mg IV increments q2–3 min","Monitor continuously — opioid may outlast naloxone (renarcotization)"],
 dP:["Initial: 0.01 mg/kg IV; if inadequate, 0.1 mg/kg; repeat q2–3 min","Narcan 4 mg nasal spray may be used at any age when IV access unavailable"],
 dur:"Single emergency event; effects last ~30–90 min, so repeated doses & observation often needed.",hl:"~30–80 min IV (~2 h intranasal)",
 se:["Acute precipitated opioid withdrawal (nausea, vomiting, sweating, agitation)","Tachycardia & hypertension","Pulmonary edema","Ventricular arrhythmias (rare)","Cardiac arrest (rare, post-op cardiac-risk patients)"],
 ix:["Opioids (all) — reverses analgesia & precipitates withdrawal in dependent patients","Long-acting opioids (methadone, fentanyl patches) — sedation/apnea can recur; repeat dosing","Buprenorphine — high affinity → partial/slow reversal; larger/repeated doses may be needed"],
 preg:"Use whenever indicated — untreated overdose can be fatal to mother & fetus (monitor for fetal distress). Minimal oral bioavailability — harm to a breastfed infant unlikely.",
 pills:[{f:"vial",s:"0.4 mg/mL injection"},{f:"nasal spray",s:"4 mg (Narcan)"}],
 src:["https://www.drugs.com/naloxone.html","https://www.drugs.com/pro/narcan.html"]},

{id:"sertraline",generic:"Sertraline",trade:["Zoloft"],cat:"Psychiatry",cls:"SSRI antidepressant",sched:null,ver:true,cond:["depression","anxiety","suicide"],
 boxed:["Increased risk of suicidal thoughts & behavior in children, teens, and young adults — monitor closely, especially early and after dose changes."],
 uses:["Major depressive disorder","Obsessive-compulsive disorder (adults & children ≥6)","Panic disorder","PTSD","Social anxiety disorder","Premenstrual dysphoric disorder"],
 dA:["Depression/OCD: start 50 mg once daily; range 50–200 mg/day","Panic, PTSD, social anxiety: start 25 mg, ↑to 50 mg after 1 week","Titrate at ≥1-week intervals; max 200 mg/day"],
 dP:["OCD, 6–12 yr: start 25 mg once daily","OCD, 13–17 yr: start 50 mg once daily; max 200 mg/day","Not approved for pediatric depression"],
 dur:"Long-term; continue ≥6–12 months after improvement, then taper — do not stop abruptly.",hl:"~26 h (active metabolite 62–104 h)",
 se:["Nausea & diarrhea","Insomnia or drowsiness","Sexual dysfunction","Tremor & sweating","Increased bleeding risk","Hyponatremia (esp. older adults)"],
 ix:["MAOIs — serotonin syndrome; contraindicated (14-day washout)","Pimozide — contraindicated (arrhythmia risk)","Other serotonergics (triptans, tramadol, linezolid) — serotonin syndrome","NSAIDs, aspirin, warfarin — ↑bleeding","Disulfiram — reacts with alcohol in oral concentrate"],
 preg:"3rd-trimester use may cause neonatal adaptation symptoms; weigh against untreated depression. Low milk levels — generally compatible with breastfeeding.",
 pills:[{f:"tablet",s:"50 mg",sh:"oval",c:"blue",im:"50",sc:true},{f:"tablet",s:"100 mg",sh:"oval",c:"yellow",im:"100",sc:true}],
 src:["https://www.drugs.com/sertraline.html","https://www.drugs.com/pro/sertraline.html"]},

{id:"escitalopram",generic:"Escitalopram",trade:["Lexapro"],cat:"Psychiatry",cls:"SSRI antidepressant",sched:null,ver:true,cond:["depression","anxiety"],
 boxed:["Increased risk of suicidal thoughts & behavior in children, teens, and young adults — monitor closely."],
 uses:["Major depressive disorder (adults & age 12+)","Generalized anxiety disorder (adults & age 7+)","Panic disorder (off-label)","Social anxiety disorder (off-label)","OCD (off-label)"],
 dA:["Depression/GAD: start 10 mg once daily","May ↑to 20 mg after ≥1 week","Max 20 mg/day; use 10 mg/day in older adults & hepatic impairment"],
 dP:["Depression, 12–17 yr: start 10 mg, ↑to 20 mg after ≥3 weeks","GAD, 7–17 yr: start 10 mg; max 20 mg/day"],
 dur:"Long-term; continue ≥6–12 months after response, then taper gradually.",hl:"~27–32 h (longer in older adults)",
 se:["Nausea","Insomnia or drowsiness","Sexual dysfunction","Sweating","Hyponatremia","QT prolongation at high doses","Increased bleeding risk"],
 ix:["MAOIs — serotonin syndrome; contraindicated","Pimozide — contraindicated; QT prolongation","QT-prolonging drugs — additive rhythm risk","Other serotonergics (triptans, tramadol, linezolid) — serotonin syndrome","NSAIDs, aspirin, anticoagulants — ↑bleeding"],
 preg:"Late-pregnancy exposure can cause neonatal adaptation problems; discuss risk vs untreated illness. Passes into breast milk — monitor infant.",
 pills:[{f:"tablet",s:"10 mg",sh:"round",c:"white",im:"FL 10",sc:true},{f:"tablet",s:"20 mg",sh:"round",c:"white",im:"FL 20",sc:true}],
 src:["https://www.drugs.com/escitalopram.html","https://www.drugs.com/monograph/escitalopram.html"]},

{id:"trazodone",generic:"Trazodone",trade:["Desyrel"],cat:"Psychiatry",cls:"Serotonin antagonist & reuptake inhibitor (SARI)",sched:null,ver:true,cond:["depression"],
 boxed:["Increased risk of suicidal thoughts & behavior in children, teens, and young adults — monitor closely."],
 uses:["Major depressive disorder","Insomnia (very common off-label, low bedtime doses)","Anxiety adjunct (off-label)"],
 dA:["Depression: start 150 mg/day divided, after meals; ↑by 50 mg q3–4 days","Max 400 mg/day outpatient; 600 mg/day inpatient","Insomnia (off-label): 25–100 mg at bedtime"],
 dP:["Not routinely used in children."],
 dur:"Depression: months after response. Insomnia: often nightly short–medium term; reassess.",hl:"~5–13 h (biphasic)",
 se:["Sedation & drowsiness","Dizziness & orthostatic hypotension","Priapism (rare — medical emergency)","Dry mouth & blurred vision","Cardiac arrhythmias (rare)","Serotonin syndrome (with serotonergics)"],
 ix:["MAOIs — serotonin syndrome; contraindicated","Alcohol & CNS depressants — additive sedation","Other serotonergics (SSRIs, triptans, tramadol) — serotonin syndrome","Strong CYP3A4 inhibitors (ritonavir, ketoconazole) — ↑levels","Antihypertensives — additive hypotension"],
 preg:"Use only if benefit justifies risk; do not stop abruptly. Small amounts in breast milk — monitor infant for sedation.",
 pills:[{f:"tablet",s:"50 mg",sh:"round",c:"white",im:"433",sc:true},{f:"tablet",s:"100 mg",sh:"round",c:"white",im:"434",sc:true}],
 src:["https://www.drugs.com/trazodone.html"]},

{id:"quetiapine",generic:"Quetiapine",trade:["Seroquel","Seroquel XR"],cat:"Psychiatry",cls:"Atypical (second-generation) antipsychotic",sched:null,ver:true,cond:["bipolar","schizophrenia","delirium"],
 boxed:["Increased mortality in elderly with dementia-related psychosis — not approved for this use.","Increased risk of suicidal thoughts & behavior in children, teens, and young adults."],
 uses:["Schizophrenia (adults & age 13+)","Bipolar mania (adults & age 10+)","Bipolar depression","Bipolar maintenance","Adjunct for major depression (XR)"],
 dA:["Schizophrenia (IR): start 25 mg BID; usual 150–750 mg/day","Schizophrenia (XR): start 300 mg once daily; usual 400–800 mg/day","Bipolar mania: titrate to 400–800 mg/day divided","Bipolar depression: titrate to 300 mg at bedtime"],
 dP:["Schizophrenia, 13–17 yr: titrate to 400–800 mg/day","Bipolar mania, 10–17 yr: titrate to 400–600 mg/day"],
 dur:"Long-term maintenance for schizophrenia & bipolar disorder; reassess periodically.",hl:"~6 h IR (metabolite norquetiapine ~12 h)",
 se:["Sedation","Weight gain, high blood sugar, high cholesterol (metabolic syndrome)","Orthostatic hypotension & dizziness","Tardive dyskinesia","Neuroleptic malignant syndrome (rare)","QT prolongation"],
 ix:["Strong CYP3A4 inhibitors (ketoconazole, ritonavir) — reduce quetiapine to ⅙ dose","CYP3A4 inducers (phenytoin, carbamazepine, rifampin) — markedly ↓levels","QT-prolonging drugs — avoid; additive rhythm risk","Alcohol & CNS depressants — additive sedation","Antihypertensives — additive hypotension"],
 preg:"3rd-trimester exposure can cause neonatal extrapyramidal/withdrawal symptoms. Very low milk levels — monitor infant for sedation.",
 pills:[{f:"tablet",s:"25 mg",sh:"round",c:"peach",im:"25",sc:false},{f:"tablet",s:"100 mg",sh:"round",c:"yellow",im:"100",sc:false}],
 src:["https://www.drugs.com/quetiapine.html","https://www.drugs.com/dosage/quetiapine.html"]},

{id:"lorazepam",generic:"Lorazepam",trade:["Ativan"],cat:"Psychiatry",cls:"Benzodiazepine",sched:"C-IV",ver:true,cond:["anxiety","withdrawal","seizure","delirium"],
 boxed:["Use with opioids can cause profound sedation, respiratory depression, coma, and death.","Risk of abuse, misuse, and addiction leading to overdose.","Physical dependence & life-threatening withdrawal with abrupt stopping — taper gradually."],
 uses:["Anxiety disorders (short-term)","Anxiety-related insomnia","Status epilepticus (IV)","Preoperative sedation","Alcohol withdrawal (off-label)"],
 dA:["Anxiety: 2–3 mg/day in 2–3 divided doses (range 1–10 mg/day)","Insomnia due to anxiety: 2–4 mg at bedtime","Status epilepticus: 4 mg IV at 2 mg/min; may repeat once (max 8 mg)","Preop: 2 mg or 0.044 mg/kg IV"],
 dP:["Status epilepticus (off-label): 0.05–0.1 mg/kg IV (max 4 mg/dose); may repeat once","Injection not FDA-approved <18 yr"],
 dur:"Short-term — typically 2–4 weeks; taper rather than stop abruptly.",hl:"~12 h (range 10–20 h)",
 se:["Drowsiness & sedation","Dizziness & weakness","Ataxia (unsteadiness, falls)","Anterograde amnesia","Respiratory depression (esp. with opioids/alcohol)","Dependence & withdrawal","Paradoxical agitation (children, elderly)"],
 ix:["Opioids — profound sedation, respiratory depression, death (boxed warning)","Alcohol — dangerous additive CNS/respiratory depression","Other CNS depressants — additive sedation","Valproate — ↑lorazepam levels; reduce dose ~50%","Probenecid — ↓clearance; reduce dose"],
 preg:"Avoid when possible — risk of neonatal sedation & withdrawal. Passes into breast milk; generally not recommended — monitor infant.",
 pills:[{f:"tablet",s:"0.5 mg",sh:"pentagon",c:"white",im:"0.5",sc:false},{f:"tablet",s:"1 mg",sh:"pentagon",c:"white",im:"1",sc:true},{f:"tablet",s:"2 mg",sh:"pentagon",c:"white",im:"2",sc:true}],
 src:["https://www.drugs.com/lorazepam.html","https://www.drugs.com/dosage/lorazepam.html"]},

{id:"acetaminophen",generic:"Acetaminophen",trade:["Tylenol","Ofirmev (IV)"],cat:"MSK & Rheum",cls:"Non-opioid analgesic / antipyretic",sched:null,ver:true,cond:["osteoarthritis","acetaminophen-od"],
 boxed:["IV form only — hepatotoxicity (acute liver failure/death, usually >4 g/day or multiple products).","IV form only — dosing errors (mg vs mL confusion) causing accidental overdose."],
 uses:["Mild–moderate pain","Fever","Headache","Osteoarthritis pain","Adjunct to opioids (incl. IV perioperative)"],
 dA:["Oral: 325–1000 mg q4–6h PRN; max 4000 mg/day","Chronic use / liver risk: ≤3000 mg/day (≤2 g/day with heavy alcohol or liver disease)","IV (≥50 kg): 1000 mg q6h or 650 mg q4h; max 4000 mg/day","IV (<50 kg): 15 mg/kg q6h"],
 dP:["Oral: 10–15 mg/kg/dose q4–6h PRN; max 5 doses (75 mg/kg) per 24 h","IV (2–12 yr): 15 mg/kg q6h; max 75 mg/kg/day"],
 dur:"Days for acute pain/fever; safe for longer scheduled use at the lower chronic max.",hl:"~2–3 h (prolonged in liver dysfunction)",
 se:["Liver damage / acute liver failure (overdose or exceeding daily max)","Severe skin reactions — SJS/TEN (rare)","Hypersensitivity / anaphylaxis (rare)","Nausea, stomach upset"],
 ix:["Warfarin — regular use >1.3 g/day for several days ↑INR & bleeding","Alcohol (chronic/heavy) — greatly ↑hepatotoxicity","Other acetaminophen combos (cold/opioid products) — cumulative overdose","Enzyme inducers (carbamazepine, phenytoin, isoniazid) — ↑liver injury risk"],
 preg:"Preferred OTC analgesic/antipyretic in pregnancy at the lowest effective dose. Compatible with breastfeeding.",
 pills:[{f:"tablet",s:"325 mg",sh:"round",c:"white",im:"325",sc:false},{f:"caplet",s:"500 mg",sh:"oblong",c:"white",im:"L484",sc:false},{f:"vial",s:"1000 mg/100 mL IV"}],
 src:["https://www.drugs.com/acetaminophen.html","https://www.drugs.com/dosage/acetaminophen.html"]},

{id:"ibuprofen",generic:"Ibuprofen",trade:["Advil","Motrin","Caldolor (IV)"],cat:"MSK & Rheum",cls:"NSAID (propionic acid)",sched:null,ver:true,cond:["osteoarthritis","ra","gout","migraine"],
 boxed:["Cardiovascular thrombotic events — ↑risk of fatal MI/stroke; contraindicated for peri-CABG pain.","GI bleeding, ulceration, perforation — can occur without warning and be fatal."],
 uses:["Mild–moderate pain","Fever","Menstrual cramps (dysmenorrhea)","Osteoarthritis / rheumatoid arthritis","Musculoskeletal injury, headache, toothache"],
 dA:["OTC pain/fever: 200–400 mg q4–6h PRN; max 1200 mg/day self-treatment","Rx pain/arthritis: 400–800 mg q6–8h; max 3200 mg/day","IV (Caldolor): 400–800 mg q6h","Use lowest effective dose for shortest duration"],
 dP:["≥6 mo: 5–10 mg/kg/dose q6–8h PRN","Max 40 mg/kg/day or 4 doses/day"],
 dur:"Shortest possible — OTC up to 10 days for pain / 3 days for fever; longer arthritis use only with supervision.",hl:"~2 h",
 se:["GI bleeding, ulcers, perforation","Heart attack / stroke risk","Acute kidney injury","Hypertension & fluid retention/edema","Bronchospasm in aspirin-sensitive asthma"],
 ix:["Anticoagulants/antiplatelets (warfarin, DOACs) — major bleeding risk","Aspirin (low-dose) — ibuprofen blunts cardioprotection; separate doses","ACEi/ARB + diuretic ('triple whammy') — acute kidney injury","Lithium & methotrexate — ↓clearance, toxicity","SSRIs/SNRIs — ↑GI bleeding"],
 preg:"Avoid at ≥20 weeks (fetal kidney injury, low amniotic fluid) and definitely ≥30 weeks (ductus closure). Compatible with breastfeeding.",
 pills:[{f:"tablet",s:"200 mg",sh:"round",c:"orange",im:"I-2",sc:false},{f:"tablet",s:"600 mg",sh:"oval",c:"white",im:"IP 465",sc:false},{f:"tablet",s:"800 mg",sh:"oblong",c:"white",im:"IP 466",sc:false}],
 src:["https://www.drugs.com/ibuprofen.html","https://www.drugs.com/dosage/ibuprofen.html"]},

{id:"oxycodone",generic:"Oxycodone",trade:["OxyContin (ER)","Roxicodone"],cat:"MSK & Rheum",cls:"Opioid analgesic (mu agonist)",sched:"C-II",ver:true,cond:["fracture"],
 boxed:["Addiction, abuse, and misuse — can lead to overdose and death.","Life-threatening respiratory depression, greatest at initiation and dose increases.","Accidental ingestion (esp. children) can be fatal.","Neonatal opioid withdrawal with prolonged use in pregnancy.","Concomitant benzodiazepines/CNS depressants — profound sedation, respiratory depression, death."],
 uses:["Moderate–severe acute pain (e.g. post-op)","Severe chronic pain needing daily around-the-clock opioid (ER)","Cancer pain","Pain unresponsive to non-opioids"],
 dA:["IR: 5–10 mg q4–6h PRN (range 5–15 mg); titrate to effect","ER (OxyContin): q12h; opioid-tolerant or carefully titrated patients","Lowest effective dose for shortest duration; taper to stop"],
 dP:["IR not routinely used in children","ER only for opioid-tolerant ≥11 yr already on ≥20 mg/day oxycodone equivalents"],
 dur:"A few days for most acute pain; chronic use only in select patients with monitoring & a taper plan.",hl:"~3–4 h (IR)",
 se:["Respiratory depression","Constipation","Nausea / vomiting","Sedation, dizziness","Physical dependence & addiction","Hypotension; confusion"],
 ix:["Benzodiazepines & CNS depressants (alcohol, gabapentinoids) — profound sedation, respiratory depression, death","CYP3A4 inhibitors (azoles, macrolides, protease inhibitors) — ↑levels, fatal respiratory depression","CYP3A4 inducers (rifampin, carbamazepine) — ↓effect / withdrawal","MAOIs — avoid within 14 days","Serotonergic drugs — serotonin syndrome"],
 preg:"Prolonged use causes neonatal opioid withdrawal (can be life-threatening). Passes into breast milk — infant sedation/respiratory depression; avoid or monitor closely.",
 pills:[{f:"tablet",s:"5 mg",sh:"round",c:"white",im:"K 18",sc:false},{f:"tablet",s:"10 mg ER",sh:"round",c:"white",im:"10",sc:false}],
 src:["https://www.drugs.com/oxycodone.html"]},

{id:"morphine",generic:"Morphine",trade:["MS Contin (ER)","Duramorph (IV)"],cat:"MSK & Rheum",cls:"Opioid analgesic (mu agonist)",sched:"C-II",ver:true,cond:["acs","sickle-cell"],
 boxed:["Addiction, abuse, and misuse — overdose and death even at prescribed doses.","Life-threatening respiratory depression.","Accidental ingestion (esp. children) can be fatal.","Neonatal opioid withdrawal with prolonged use in pregnancy.","Concomitant benzodiazepines/alcohol/CNS depressants — profound sedation, respiratory depression, death."],
 uses:["Severe acute pain (trauma, post-op, MI)","Cancer pain","Severe chronic pain needing around-the-clock opioid (ER)","Dyspnea palliation in end-of-life care"],
 dA:["Oral IR: 15–30 mg q4h PRN","IV: 0.1–0.2 mg/kg slow IV q4h PRN (~2–10 mg per 70 kg)","ER (MS Contin): q8–12h for opioid-tolerant chronic pain","Oral:IV potency ~3:1"],
 dP:["Specialist/hospital use only; weight-based (e.g. 0.1 mg/kg IV q4–6h in older infants/children)"],
 dur:"Hours–days for acute pain; chronic use reserved for cancer/palliative with monitoring.",hl:"~1.5–2 h (analgesia ~4 h)",
 se:["Respiratory depression","Constipation","Nausea / vomiting","Sedation, dizziness","Hypotension; histamine release (itching, flushing)","Dependence & addiction; miosis"],
 ix:["Benzodiazepines & CNS depressants — profound sedation, respiratory depression, death","MAOIs — severe reactions; avoid within 14 days","Serotonergic drugs (SSRIs, tramadol) — serotonin syndrome","Muscle relaxants — enhanced respiratory depression","Diuretics/antihypertensives — additive hypotension"],
 preg:"Prolonged use causes neonatal opioid withdrawal. Enters breast milk — infant sedation/respiratory depression; breastfeeding generally discouraged during ongoing use.",
 pills:[{f:"tablet",s:"15 mg IR",sh:"round",c:"white",im:"15",sc:false},{f:"tablet",s:"30 mg IR",sh:"round",c:"white",im:"30",sc:false},{f:"vial",s:"IV 2–10 mg/mL"}],
 src:["https://www.drugs.com/morphine.html","https://www.drugs.com/dosage/morphine.html"]},

{id:"fentanyl",generic:"Fentanyl",trade:["Duragesic (patch)","Sublimaze (IV)"],cat:"Emergency & Surgical",cls:"Synthetic opioid analgesic (~100× morphine)",sched:"C-II",ver:true,cond:["shock"],
 boxed:["Addiction, abuse, and misuse — overdose and death.","Life-threatening respiratory depression.","Accidental exposure to a patch (even used) can be fatal, especially in children.","Patch: external heat on the site has caused fatal overdose.","Patch is for opioid-TOLERANT patients only.","CYP3A4 inhibitor interactions can cause fatal overdose.","Neonatal opioid withdrawal with prolonged use in pregnancy.","Concomitant benzodiazepines/CNS depressants — profound sedation, respiratory depression, death."],
 uses:["IV: anesthesia & perioperative analgesia","IV: procedural sedation & ICU analgosedation","Patch: severe chronic pain in opioid-tolerant patients","Transmucosal: breakthrough cancer pain"],
 dA:["IV periop: 25–100 mcg slow IV; low-dose anesthesia ~2 mcg/kg","Patch: opioid-tolerant only; commonly start 25 mcg/h, change q72h","Patch strengths: 12, 25, 37.5, 50, 62.5, 75, 87.5, 100 mcg/h","Titrate patch no sooner than q3 days; effect persists after removal (skin depot)"],
 dP:["Patch: only opioid-tolerant children ≥2 yr","IV: weight-based (~1–2 mcg/kg) by specialists only"],
 dur:"IV effect minutes–hours (periop); each patch worn 72 h, chronic use under specialist care.",hl:"IV terminal ~3.7 h; patch levels fall ~50% over ~17 h after removal",
 se:["Respiratory depression / apnea","Sedation, dizziness, confusion","Constipation","Nausea / vomiting","Bradycardia, hypotension; chest-wall rigidity with rapid IV bolus","Dependence & addiction; miosis"],
 ix:["Benzodiazepines / CNS depressants / alcohol — profound sedation, respiratory depression, death","CYP3A4 inhibitors (azoles, macrolides, protease inhibitors) — ↑levels, fatal respiratory depression","CYP3A4 inducers — ↓effect; toxicity if inducer withdrawn","MAOIs — avoid within 14 days","External heat on patch site — accelerated absorption, overdose"],
 preg:"Prolonged use causes life-threatening neonatal opioid withdrawal. Passes into breast milk — breastfeeding not recommended during treatment.",
 pills:[{f:"patch",s:"25 mcg/h (transdermal)"},{f:"vial",s:"50 mcg/mL IV"}],
 src:["https://www.drugs.com/fentanyl.html","https://www.drugs.com/pro/duragesic.html"]}
];
