// preview/illus-real.js — real/AI images that OVERRIDE schematic SVGs.
// Generated by tools/incorporate_images.py. Loaded LAST so RC_ILLUS[id] here wins.
// Each image is physician-reviewed; ECGs stay vector unless --include-ecg.
Object.assign(window.RC_ILLUS = window.RC_ILLUS || {}, {
});
