/* Add a Listen button and audio player to every condition that has a narration file.
 *
 * Usage: node scripts/add_audio_player.js <index.html> [--ids chf,acs,afib]
 *
 * Design notes, because several of these are easy to get wrong:
 *
 * ONE shared <audio> element, not one per render. detailHTML() runs on every paint, so an element
 * in the template would mean a fresh player each time and, worse, two overlapping playbacks if the
 * user re-entered the page mid-track.
 *
 * PLAYBACK STOPS WHEN YOU LEAVE THE CONDITION. This is the bug worth preventing: without it, audio
 * for Heart Failure keeps narrating while the user reads Asthma. paint() is the single choke point
 * -- go(), back(), root() and setMode() all funnel through it -- and it already calls closeViewer()
 * for exactly this reason, so the stop hook sits alongside that. Playback survives a repaint that
 * stays on the same condition, so switching mode mid-track does not cut it off.
 *
 * AUDIO IS **NOT** ADDED TO sw.js CORE. That was my first instinct and it is wrong: CORE is
 * precached with addAll() at install, so listing 181 narration files would try to download the
 * entire audio library on a first visit -- hundreds of megabytes before the app opens. The existing
 * fetch handler is already network-first with a cache write for assets, so each file is cached the
 * first time it is played and is then available offline. Nothing to change in the service worker.
 *
 * RC_AUDIO lives in code rather than content/*.json on purpose. Adding an eighth content file means
 * touching the boot loader and CORE, and this list is machine-maintained -- re-run this script with
 * --ids when a batch of narration ships -- so it is generated, not hand-edited.
 */
'use strict';
const fs = require('fs');

const [, , FILE, ...rest] = process.argv;
if (!FILE) {
  console.error('usage: add_audio_player.js <index.html> [--ids a,b,c]');
  process.exit(2);
}
const idsArg = rest.includes('--ids') ? rest[rest.indexOf('--ids') + 1] : '';
const IDS = idsArg ? idsArg.split(',').map(s => s.trim()).filter(Boolean) : [];

let s = fs.readFileSync(FILE, 'utf8');
const before = s.length;

function replaceOnce(str, find, repl, what) {
  const n = str.split(find).length - 1;
  if (n !== 1) {
    console.error(`FAILED (${what}): found ${n} occurrences, expected exactly 1`);
    process.exit(1);
  }
  console.log(`  ok  ${what}`);
  return str.replace(find, repl);
}

/* ------------------------------------------------------------------ 1. the registry + player */
const RUNTIME = `
/* ---- narration audio -------------------------------------------------------------
   RC_AUDIO is generated by scripts/add_audio_player.js; do not hand-edit.
   Files live at assets/audio/<id>.mp3 and are cached by the service worker on first
   play -- deliberately NOT precached, since the whole library is far too large to
   pull down at install. */
const RC_AUDIO = ${JSON.stringify(IDS)};
let _rcAudId = null;
function _rcAudEl(){
  let a = document.getElementById('rcAud');
  if (!a) {
    a = document.createElement('audio');
    a.id = 'rcAud'; a.preload = 'none';
    // a missing or unplayable file must say so rather than fail silently
    a.addEventListener('error', () => { _rcAudId = null; rcAudioPaint(); toast('Narration unavailable'); });
    a.addEventListener('ended', () => { _rcAudId = null; rcAudioPaint(); });
    a.addEventListener('play', rcAudioPaint);
    a.addEventListener('pause', rcAudioPaint);
    document.body.appendChild(a);
  }
  return a;
}
function rcAudioToggle(id){
  const a = _rcAudEl();
  if (_rcAudId === id && !a.paused) { a.pause(); return; }
  if (_rcAudId !== id) { a.pause(); a.src = (window.RC_ROOT||'') + 'assets/audio/' + id + '.mp3'; _rcAudId = id; }
  a.play().catch(() => { _rcAudId = null; rcAudioPaint(); toast('Narration unavailable'); });
}
function rcAudioStop(){
  const a = document.getElementById('rcAud');
  if (a && !a.paused) a.pause();
  _rcAudId = null;
  rcAudioPaint();
}
function rcAudioPaint(){
  const b = document.querySelector('.d-listen');
  if (!b) return;
  const a = document.getElementById('rcAud');
  const playing = a && !a.paused && _rcAudId === b.getAttribute('data-aud');
  b.setAttribute('aria-pressed', playing ? 'true' : 'false');
  b.querySelector('.d-listen-t').textContent = playing ? 'Pause' : 'Listen';
}
`;

s = replaceOnce(s,
  'function toast(t){',
  RUNTIME + 'function toast(t){',
  'RC_AUDIO registry and player runtime added before toast()');

/* ------------------------------------------------------------ 2. the button on the detail page */
const SHARE = `<button class="d-share" onclick="rcShare('\${id}')"`;
const LISTEN = '${RC_AUDIO.indexOf(id)>=0?`<button class="d-listen" data-aud="${id}" ' +
  'aria-pressed="false" onclick="rcAudioToggle(\'${id}\')" aria-label="Listen to the ${String(d.name).replace(/"/g,\'&quot;\')} module">' +
  '<svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="2.2" ' +
  'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 5L6 9H2v6h4l5 4V5z"/>' +
  '<path d="M15.5 8.5a5 5 0 010 7"/></svg><span class="d-listen-t">Listen</span></button>`:\'\'}';

s = replaceOnce(s, SHARE, LISTEN + SHARE,
  'Listen button injected into the ICD/share row, only for ids with narration');

/* --------------------------------------------------- 3. stop playback when leaving the condition */
s = replaceOnce(s,
  `function paint(y){\n const r=stack[stack.length-1],s=document.getElementById('screen');closeViewer();`,
  `function paint(y){\n const r=stack[stack.length-1],s=document.getElementById('screen');closeViewer();` +
  `  /* Narration must not keep playing over a different condition. Keep it only when the view` +
  `     being painted is still the detail page for the track that is playing, so a mode switch` +
  `     mid-track survives but any navigation away stops it. */` +
  `  if(_rcAudId && !(r.v==='detail' && r.id===_rcAudId)) rcAudioStop();`,
  'paint() stops narration when the visible condition changes');

/* ------------------------------------------------------------------------------ 4. the styling */
s = replaceOnce(s,
  '.d-icd{display:inline-block;',
  `.d-listen{display:inline-flex;align-items:center;gap:6px;border:1px solid var(--line);` +
  `background:rgba(255,255,255,.04);color:var(--accent);border-radius:9px;padding:5px 10px;` +
  `font:inherit;font-size:12.5px;font-weight:800;cursor:pointer;margin-top:12px;margin-right:8px}` +
  `.d-listen[aria-pressed="true"]{background:var(--accent);color:#04121a;border-color:var(--accent)}` +
  `.d-listen:focus-visible{outline:2px solid var(--accent);outline-offset:2px}` +
  '.d-icd{display:inline-block;',
  'Listen button styling, using --accent (the MODE colour) like the Share button');

fs.writeFileSync(FILE, s);
console.log(`\n${IDS.length} condition(s) with narration: ${IDS.join(', ') || '(none yet)'}`);
console.log(`${FILE}: ${before} -> ${s.length} bytes`);
console.log('sw.js unchanged on purpose — audio is runtime-cached, never precached.');
