#!/usr/bin/env node
/* Emit a ba-package manifest for each asset pack, plus the script that packages them.
 *
 * Task #27. Input is native/asset-packs.json from scripts/plan_asset_packs.js; output is one
 * manifest per pack and a shell script that runs `ba-package create` over all of them.
 *
 * THE SCHEMA IS NOT INVENTED. It is the template printed by `ba-package template`, quoted verbatim
 * in Apple's WWDC25 session 325 ("Discover Apple-Hosted Background Assets"):
 *
 *   { "assetPackID": ..., "downloadPolicy": { "essential": { "installationEventTypes": [...] } },
 *     "fileSelectors": [ {"file": ...}, {"directory": ...} ], "platforms": [...] }
 *
 * That matters because the alternative was writing a plausible-looking schema from memory and
 * handing it to someone to run in Xcode -- the failure mode this project keeps getting bitten by.
 * If `ba-package template` on a real machine prints anything different, IT wins: run it, diff it
 * against this, and fix the generator rather than hand-editing eleven files.
 *
 * DOWNLOAD POLICY. Three are available and the choice is a product decision, not a technical one:
 *
 *   essential  downloaded during installation; the app will not launch until it finishes. Wrong
 *              here -- it would throw away the whole point of an 84 MB install by making the
 *              reader wait for 742 MB before they see anything.
 *   prefetch   downloaded in the background straight after install. Honest offline story, but it
 *              pulls all 742 MB onto every device whether or not the reader wants ten specialties
 *              they will never open.
 *   onDemand   downloaded when the app asks. DEFAULT HERE, because RC_MEDIA_ROOT's fallback already
 *              makes an un-downloaded pack stream from the public origin rather than break, so the
 *              app can request a category the moment a reader opens a gallery in it and still work
 *              in the meantime. It also leaves room for an explicit "download for offline" control,
 *              which is the version a student with a full phone actually wants.
 *
 * Override with --policy prefetch|essential if that judgement changes.
 *
 * Usage: node scripts/build_asset_pack_manifests.js <packs.json> <out-dir> [--policy onDemand]
 */
'use strict';
const fs = require('fs');
const path = require('path');

const IN = process.argv[2], OUT = process.argv[3];
const pAt = process.argv.indexOf('--policy');
const POLICY = pAt > -1 ? process.argv[pAt + 1] : 'onDemand';
if (!IN || !OUT) {
  console.error('usage: build_asset_pack_manifests.js <packs.json> <out-dir> [--policy onDemand]');
  process.exit(2);
}
if (!['onDemand', 'prefetch', 'essential'].includes(POLICY)) {
  console.error(`FAIL: unknown download policy ${JSON.stringify(POLICY)}`);
  process.exit(1);
}

const plan = JSON.parse(fs.readFileSync(IN, 'utf8'));
if (!Array.isArray(plan.packs) || !plan.packs.length) {
  console.error('FAIL: no packs in the plan file'); process.exit(1);
}
fs.mkdirSync(OUT, { recursive: true });

/* onDemand is an empty object; the other two carry installationEventTypes. Straight from the
   template -- do not "tidy" onDemand into null, the field has to be present. */
const downloadPolicy = POLICY === 'onDemand'
  ? { onDemand: {} }
  : { [POLICY]: { installationEventTypes: ['firstInstallation', 'subsequentUpdate'] } };

const written = [];
for (const p of plan.packs) {
  if (!/^[a-z0-9][a-z0-9-]*$/.test(p.id)) {
    console.error(`FAIL: ${p.id} is not a safe asset pack id`); process.exit(1);
  }
  if (!p.files || !p.files.length) { console.error(`FAIL: ${p.id} has no files`); process.exit(1); }
  /* Explicit file selectors rather than directory ones. A directory selector is shorter and would
     sweep in whatever else happens to sit in that folder -- and this tree has already shown it
     keeps things in odd places (the *-upload directories, loose root JPEGs, a stale duplicate of
     eight galleries). The pack should contain exactly the files the plan resolved, no more. */
  const manifest = {
    assetPackID: p.id,
    downloadPolicy,
    fileSelectors: p.files.map(f => ({ file: f })),
    platforms: ['iOS'],
  };
  const out = path.join(OUT, `${p.id}.json`);
  fs.writeFileSync(out, JSON.stringify(manifest, null, 2) + '\n');
  written.push({ id: p.id, files: p.files.length, bytes: p.bytes, out });
}

/* The runner. Written rather than described, because eleven invocations typed by hand is eleven
   chances to fumble one -- and it is the physician who will be running them. */
const sh = [
  '#!/bin/sh',
  '# Package every Rounds Codex asset pack. Generated by scripts/build_asset_pack_manifests.js.',
  '#',
  '# Run from the ROOT OF THE SITE TREE -- fileSelectors are relative paths from where this runs,',
  '# so running it from anywhere else silently produces packs that are missing every file.',
  '#',
  '# On macOS with Xcode:   BA="xcrun ba-package"',
  '# On Linux/Windows:      BA="ba-package"   (Managed Background Assets Developer Tools)',
  'set -e',
  ': "${BA:=xcrun ba-package}"',
  ': "${MANIFESTS:=' + path.resolve(OUT) + '}"',
  ': "${OUTDIR:=./asset-packs}"',
  'mkdir -p "$OUTDIR"',
  '',
  ...written.map(w =>
    `echo "==> ${w.id}  (${w.files} files, ${(w.bytes / 1048576).toFixed(1)} MB)"\n` +
    `$BA create --manifest "$MANIFESTS/${w.id}.json" --output "$OUTDIR/${w.id}.aar"`),
  '',
  'echo "done: $(ls -1 "$OUTDIR" | wc -l) pack(s) in $OUTDIR"',
].join('\n') + '\n';
const shPath = path.join(OUT, 'package-all.sh');
fs.writeFileSync(shPath, sh, { mode: 0o755 });

/* Sanity: every manifest must be valid JSON with the four required keys, and the file lists must
   add up to the plan. A generator that silently drops a pack is worse than one that throws. */
let files = 0;
for (const w of written) {
  const m = JSON.parse(fs.readFileSync(w.out, 'utf8'));
  for (const k of ['assetPackID', 'downloadPolicy', 'fileSelectors', 'platforms'])
    if (!(k in m)) { console.error(`FAIL: ${w.id} manifest is missing ${k}`); process.exit(1); }
  files += m.fileSelectors.length;
}
const expect = plan.packs.reduce((a, p) => a + p.files.length, 0);
if (files !== expect) { console.error(`FAIL: ${files} selectors written, plan has ${expect} files`); process.exit(1); }

console.log(`${written.length} manifests, policy "${POLICY}", ${files} file selectors\n`);
for (const w of written)
  console.log(`  ${w.id.padEnd(24)} ${String(w.files).padStart(5)} files  ${(w.bytes / 1048576).toFixed(1).padStart(7)} MB`);
console.log(`\nwritten to ${OUT}/  (+ package-all.sh)`);
console.log('\nThe archives are NOT built here: ba-package is macOS/Xcode or the Linux developer');
console.log('tools, and neither is available in this container. Run package-all.sh from the site root.');
