#!/usr/bin/env python3
"""Regenerate galleries-staging/GALLERY-GAP.md from the live app's own content files.

    python3 scripts/gen_gallery_gap.py [<app-root>]

The doc has always been described as "generated from the live app -- regenerate it, don't edit
it", but the generator was never committed, so in practice it was hand-patched and drifted:
it read 55 of 181 while the app was on 63, and listed Heme & Onc as 0/7 the day all seven
shipped. A coverage doc that is behind is worse than none, because the next batch gets planned
off it.

Reads content/conditions.json and content/galleries.json and nothing else, so it cannot
disagree with what is deployed. The prose at the end is fixed text -- it is guidance for
whoever sends the next batch, not derived data.
"""
import json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = sys.argv[1] if len(sys.argv) > 1 else '/workspace/rounds-codex-app'
OUT = os.path.join(ROOT, 'galleries-staging', 'GALLERY-GAP.md')

TAIL = """## What to send, and how

A folder named exactly the condition id, containing `<id>-01` … `<id>-10` plus a `titles.json`,
or an approved production PDF. **Send all ten pages** — a partial set cannot be built, because each
page header reads `IMAGE n OF 10`.

Notes that have cost time:

- **1024x1536, one size per gallery.** Four galleries in the 2026-08-01 batch arrived at
  1023x1537; the builder resamples, but it is a change in what production exports.
- **Page order comes from the `IMAGE n OF 10` header, not filenames** — every batch has arrived shuffled.
- **Diff against the live artwork first.** Three of six batches were wholly or largely re-sends.
- **Check the logo lockup** (`scripts/fix_page_logo.py` redraws the canonical one).
- **Check the header progress dots** — ONE filled dot at the current page. Still wrong as of
  2026-08-01 and wrong differently in each batch; see `DOTS-defect-for-production.md`. Flag for
  re-render, never repaint the delivered pages.
- **Read the subtitles for typos.** Hyponatremia page 9 shipped with "MAᓎNGEMENT"; the 2026-08-01
  batch had "deteroration", "bloodgd" and "multidiscipliinary" inside the artwork.
"""


def main():
    D = json.load(open(os.path.join(APP, 'content/conditions.json'), encoding='utf-8'))
    G = json.load(open(os.path.join(APP, 'content/galleries.json'), encoding='utf-8'))['galleries']

    cats = {}
    for c in D:
        cats.setdefault(c['category'], []).append(c)
    have = sum(1 for c in D if c['id'] in G)

    L = ['# Gallery coverage — what still needs artwork', '',
         'Generated by `scripts/gen_gallery_gap.py` from the live app: '
         f'**{have} of {len(D)} conditions have a gallery**, {len(D) - have} do not.',
         'Every gallery currently live is 10 pages at 1024x1536.', '',
         '## Summary by category', '', '| category | have | need |', '|---|---:|---:|']
    for cat in sorted(cats):
        h = sum(1 for c in cats[cat] if c['id'] in G)
        L.append(f'| {cat} | {h} | {len(cats[cat]) - h} |')
    L += [f'| **total** | **{have}** | **{len(D) - have}** |', '',
          '## Conditions needing a gallery', '',
          'The id in backticks is the folder name to use.', '']

    for cat in sorted(cats):
        need = [c for c in cats[cat] if c['id'] not in G]
        if not need:
            continue
        L += [f'### {cat} ({len(need)})', '']
        L += [f"- [ ] {c['name']} — `{c['id']}`" for c in need]
        L.append('')

    done = [(cat, len(cs)) for cat in sorted(cats) for cs in [cats[cat]]
            if all(c['id'] in G for c in cs)]
    L += ['## Categories already complete', '']
    L += [f'- {cat} ({n})' for cat, n in done] or ['- (none yet)']
    L += ['', TAIL]

    open(OUT, 'w', encoding='utf-8').write('\n'.join(L))
    print(f'{OUT}: {have}/{len(D)} covered, {len(done)} categories complete')


if __name__ == '__main__':
    main()
