#!/usr/bin/env python3
"""Aggregate the label-QA agents' PAGE blocks into one ranked triage document.

The sweep of 2026-08-06 ran twelve agents over 119 gallery pages, each reporting in the
fixed format defined in the agent brief:

    PAGE <gid> <page> <WRONG|SUSPECT|UNREADABLE|clean> <n_labels> <n_not_ok>
      <VERDICT> "<label>" -> lands on: <x> | expected: <y>

This reads one or more files of those blocks (agent replies concatenated verbatim, other
prose ignored) and emits the worklist ordered the way it has to be acted on: WRONG first,
because a leader line on the wrong structure teaches the wrong anatomy, then SUSPECT,
then UNREADABLE. Clean pages are counted, not listed.

Ordering within a verdict is by gallery so that a re-render request groups by production
job rather than scattering one page across three emails.

Usage:
  python3 scripts/qa_label_report.py /tmp/qa-raw/*.txt --out galleries-staging/LABEL-QA.md
"""
import argparse, json, os, re, sys
from collections import defaultdict

PAGE_RE = re.compile(
    r"^\s*PAGE\s+([a-z0-9-]+)\s+(\d+)\s+(WRONG|SUSPECT|UNREADABLE|clean)\s+(\d+)\s+(\d+)\s*$",
    re.I)
# The chunk between the closing quote and the arrow is optional and is where the agents put a
# panel note - `SUSPECT "Ileocecal valve" [RLQ panel] -> lands on: ...`. An earlier version of
# this regex required the arrow immediately after the quote and silently dropped 184 of 323
# findings, which read as a much cleaner audit than it was. Keep the note; a finding that names
# its panel is more useful to whoever re-renders the page, not less.
FIND_RE = re.compile(
    r"^\s+(WRONG|SUSPECT|UNREADABLE)\s+[\"“](.+?)[\"”]\s*(.*?)->\s*(.*)$", re.I)

RANK = {"WRONG": 0, "SUSPECT": 1, "UNREADABLE": 2, "CLEAN": 3}


def parse(paths):
    pages, cur = [], None
    for p in paths:
        for raw in open(p, encoding="utf-8", errors="replace"):
            line = raw.rstrip("\n")
            m = PAGE_RE.match(line)
            if m:
                gid, page, verdict, n, nbad = m.groups()
                cur = {"gid": gid, "page": int(page), "verdict": verdict.upper(),
                       "n_labels": int(n), "n_not_ok": int(nbad), "findings": [],
                       "src": os.path.basename(p)}
                pages.append(cur)
                continue
            m = FIND_RE.match(line)
            if m and cur is not None:
                cur["findings"].append({"verdict": m.group(1).upper(),
                                        "label": m.group(2).strip(),
                                        "panel": m.group(3).strip(),
                                        "detail": m.group(4).strip()})
    return pages


def titles(site):
    """gid -> {page: title}, so the report names the page the physician will open."""
    try:
        G = json.load(open(os.path.join(site, "content", "galleries.json")))["galleries"]
    except Exception:
        return {}
    return {gid: {int(i["n"]): i["title"] for i in g["images"]} for gid, g in G.items()}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+")
    ap.add_argument("--out", default="-")
    ap.add_argument("--site", default="/workspace/rounds-codex-app")
    # The Word report is built from this, by scripts/build_label_qa_docx.js. It used to be
    # produced by a separate ad-hoc step, which meant the doc could silently describe a
    # different sweep from the markdown. One parse, two outputs.
    ap.add_argument("--json", help="also write the shape build_label_qa_docx.js reads")
    a = ap.parse_args()

    pages = parse(a.files)
    if not pages:
        sys.exit("no PAGE blocks found - check the input files")

    # A page reported twice (an agent retried, or two batches overlapped) keeps the worse
    # verdict rather than whichever was parsed last.
    best = {}
    for p in pages:
        k = (p["gid"], p["page"])
        if k not in best or RANK[p["verdict"]] < RANK[best[k]["verdict"]]:
            best[k] = p
    pages = list(best.values())

    T = titles(a.site)
    buckets = defaultdict(list)
    for p in pages:
        buckets[p["verdict"]].append(p)
    for v in buckets:
        buckets[v].sort(key=lambda p: (p["gid"], p["page"]))

    n_find = sum(len(p["findings"]) for p in pages)
    out = []
    W = out.append
    W("# Gallery label QA — leader lines that do not land on the structure they name")
    W("")
    W("Generated by `scripts/qa_label_report.py`. **Candidate list, not a verdict** — every")
    W("line below needs the physician's confirmation before it goes to production, and the")
    W("agents were told to report `SUSPECT` rather than guess, so the SUSPECT section is")
    W("expected to contain correct pages.")
    W("")
    W(f"- pages examined: **{len(pages)}**")
    for v in ("WRONG", "SUSPECT", "UNREADABLE", "CLEAN"):
        if buckets.get(v):
            W(f"- {v.lower()}: **{len(buckets[v])}**")
    W(f"- individual label findings: **{n_find}**")
    W("")
    W("---")
    for v, heading, blurb in (
        ("WRONG", "## 1. WRONG — re-render",
         "The line ends on a structure other than the one named. This teaches the wrong "
         "anatomy and is the defect the physician reported."),
        ("SUSPECT", "## 2. SUSPECT — needs a second look",
         "Endpoint ambiguous, between two structures, or close-but-off. Some of these will "
         "be fine."),
        ("UNREADABLE", "## 3. UNREADABLE — could not be traced",
         "Not necessarily wrong. Worth a human glance at full size."),
    ):
        rows = buckets.get(v) or []
        if not rows:
            continue
        W("")
        W(heading)
        W("")
        W(blurb)
        W("")
        for p in rows:
            t = T.get(p["gid"], {}).get(p["page"], "")
            W(f"### `{p['gid']}` page {p['page']}" + (f" — {t}" if t else ""))
            W("")
            W(f"{p['n_not_ok']} of {p['n_labels']} labels flagged.")
            W("")
            for f in p["findings"]:
                pan = f" {f['panel']}" if f.get("panel") else ""
                W(f"- **{f['verdict']}** — \"{f['label']}\"{pan} — {f['detail']}")
            W("")
    if buckets.get("CLEAN"):
        W("")
        W("## Clean")
        W("")
        W(", ".join(f"`{p['gid']}` p{p['page']}" for p in buckets["CLEAN"]))
        W("")

    if a.json:
        T2 = titles(a.site)
        rows = [{
            "gid": p["gid"], "page": p["page"], "verdict": p["verdict"],
            "n": p["n_labels"], "nbad": p["n_not_ok"],
            "title": T2.get(p["gid"], {}).get(p["page"], ""),
            # the docx wants "lands on" and "expected" as separate columns
            "f": [{
                "v": f["verdict"], "label": f["label"], "panel": f.get("panel", ""),
                "lands": re.sub(r"^lands on:\s*", "", f["detail"].split("| expected:")[0].strip(), flags=re.I),
                "exp": (f["detail"].split("| expected:")[1].strip()
                        if "| expected:" in f["detail"] else ""),
            } for f in p["findings"]],
        } for p in sorted(pages, key=lambda p: (RANK[p["verdict"]], p["gid"], p["page"]))]
        json.dump(rows, open(a.json, "w"), indent=1)
        print(f"wrote {a.json}: {len(rows)} pages, {sum(len(r['f']) for r in rows)} findings")

    text = "\n".join(out)
    if a.out == "-":
        print(text)
    else:
        open(a.out, "w").write(text)
        print(f"wrote {a.out}: {len(pages)} pages, {n_find} findings")


if __name__ == "__main__":
    main()
