#!/usr/bin/env node
/**
 * setup_android_project.js — turn the stock `cap add android` output into ours.
 *
 *   node scripts/setup_android_project.js <native-repo>
 *
 * Idempotent, and every edit is behind an exact-count guard. Run it again after a future
 * `cap sync` or a Capacitor upgrade regenerates the template.
 *
 * WHAT IT DOES, and why each one is not optional:
 *
 * 1. THE APP LINKS INTENT FILTER. Pasted verbatim from `native/android/intent-filters.xml`, which
 *    is the canonical source for the six deep-link prefixes and is what `verify_routes.js` checks
 *    against the other four places a route has to be declared. It goes ALONGSIDE the LAUNCHER
 *    filter, never replacing it -- an activity can carry several. `autoVerify="true"` is what makes
 *    Android fetch assetlinks.json at install; without it links still work but only through a
 *    disambiguation dialog most people dismiss.
 *
 * 2. THE LAUNCHER ICONS. Capacitor ships its own mark. Ours come from
 *    `native/android/res/`, generated by `make_android_icons.py` from the same
 *    `icon-maskable-512.png` as the Play store icon.
 *
 *    THE REFERENCES ALREADY MATCH, which is why this is a copy and not a rewrite: Capacitor's
 *    `mipmap-anydpi-v26/ic_launcher.xml` points at `@mipmap/ic_launcher_foreground` and
 *    `@color/ic_launcher_background`, and so does ours. Ours adds a `<monochrome>` layer that
 *    Capacitor's lacks, which is what Android 13+ themed icons use.
 *
 * 3. TWO DEAD TEMPLATE DRAWABLES REMOVED. `drawable-v24/ic_launcher_foreground.xml` and
 *    `drawable/ic_launcher_background.xml` are Android Studio template leftovers that nothing
 *    references -- grepped, not assumed; the only reference in the tree is to the COLOR resource.
 *    They are removed because a dead vector sharing a name with a live PNG is exactly the thing
 *    that wastes an hour later.
 *
 * WHAT IT DELIBERATELY DOES NOT TOUCH: `android:allowBackup`, which is a decision for the
 * physician (Auto Backup copies the WebView's localStorage to the user's Drive), and the splash
 * screens, which `make_android_splash.py` owns.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const REPO = process.argv[2];
if (!REPO) { console.error('usage: setup_android_project.js <native-repo>'); process.exit(2); }
const HERE = path.resolve(__dirname, '..');
const RES_SRC = path.join(HERE, 'native', 'android', 'res');
const FILTER_SRC = path.join(HERE, 'native', 'android', 'intent-filters.xml');
const MANIFEST = path.join(REPO, 'android', 'app', 'src', 'main', 'AndroidManifest.xml');
const RES_DST = path.join(REPO, 'android', 'app', 'src', 'main', 'res');

for (const p of [RES_SRC, FILTER_SRC, MANIFEST, RES_DST]) {
  if (!fs.existsSync(p)) { console.error(`FAIL: missing ${p}`); process.exit(1); }
}

/* ---- 1. the intent filter ------------------------------------------------------------- */
let man = fs.readFileSync(MANIFEST, 'utf8');

/* The canonical file is a commented spec; take only the element. */
const m = fs.readFileSync(FILTER_SRC, 'utf8').match(/<intent-filter[\s\S]*<\/intent-filter>/);
if (!m) { console.error(`FAIL: no <intent-filter> element in ${FILTER_SRC}`); process.exit(1); }
/* Re-indent to match the LAUNCHER filter beside it: the element at 12, its children at 16.
   The canonical file is indented for reading on its own, not for sitting inside an <activity>. */
const FILTER = m[0].split('\n').map(l => {
  const t = l.trim();
  if (!t) return l;
  return (t.startsWith('<intent-filter') || t.startsWith('</intent-filter')
    ? ' '.repeat(12) : ' '.repeat(16)) + t;
}).join('\n');

/* Anchor on the END of the LAUNCHER filter, so ours lands inside the same <activity>. */
const ANCHOR = `            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>`;

if (man.includes('android:host="roundscodex.com"')) {
  console.log('  --  intent filter already present');
} else {
  const n = man.split(ANCHOR).length - 1;
  if (n !== 1) {
    console.error(`FAIL: LAUNCHER intent-filter anchor found ${n} time(s), expected 1.\n` +
                  '      The Capacitor template changed shape -- re-read it before editing.');
    process.exit(1);
  }
  man = man.replace(ANCHOR, ANCHOR + '\n\n' + FILTER);
  fs.writeFileSync(MANIFEST, man);
  console.log('  ok  App Links intent filter added (6 prefixes, roundscodex.com, autoVerify)');
}

/* ---- 2. the icons --------------------------------------------------------------------- */
let copied = 0;
for (const dir of fs.readdirSync(RES_SRC)) {
  const from = path.join(RES_SRC, dir), to = path.join(RES_DST, dir);
  if (!fs.statSync(from).isDirectory()) continue;
  fs.mkdirSync(to, { recursive: true });
  for (const f of fs.readdirSync(from)) {
    fs.copyFileSync(path.join(from, f), path.join(to, f));
    copied++;
  }
}
console.log(`  ok  ${copied} icon file(s) copied over the template's`);

/* ---- 3. the dead template drawables --------------------------------------------------- */
const DEAD = ['drawable-v24/ic_launcher_foreground.xml', 'drawable/ic_launcher_background.xml'];
for (const rel of DEAD) {
  const p = path.join(RES_DST, rel);
  if (!fs.existsSync(p)) { console.log(`  --  ${rel} already gone`); continue; }
  /* Never delete something still referenced. Check rather than trust the comment above. */
  const name = path.basename(rel, path.extname(rel));
  const refs = [];
  (function walk(d) {
    for (const f of fs.readdirSync(d)) {
      const full = path.join(d, f);
      if (fs.statSync(full).isDirectory()) { walk(full); continue; }
      if (!full.endsWith('.xml') || full === p) continue;
      if (fs.readFileSync(full, 'utf8').includes(`@drawable/${name}`)) refs.push(full);
    }
  })(RES_DST);
  if (refs.length) {
    console.error(`FAIL: ${rel} is referenced by:\n      ${refs.join('\n      ')}`);
    process.exit(1);
  }
  fs.unlinkSync(p);
  console.log(`  ok  removed dead template drawable ${rel}`);
}

/* ---- assert the result ---------------------------------------------------------------- */
const out = fs.readFileSync(MANIFEST, 'utf8');
const checks = [
  ['LAUNCHER filter survives', out.includes('android.intent.category.LAUNCHER')],
  ['autoVerify set', out.includes('<intent-filter android:autoVerify="true">')],
  ['roundscodex.com is the only host', (out.match(/android:host="/g) || []).length === 1],
  ['all six prefixes', ['c', 's', 'g', 'r', 'u', 'x']
    .every(k => out.includes(`android:pathPrefix="/${k}/"`))],
  ['singleTask kept', out.includes('android:launchMode="singleTask"')],
  ['no AD_ID permission', !out.includes('AD_ID')],
  ['monochrome layer present',
    fs.readFileSync(path.join(RES_DST, 'mipmap-anydpi-v26', 'ic_launcher.xml'), 'utf8')
      .includes('<monochrome')],
];
let bad = 0;
console.log('');
for (const [what, ok] of checks) { console.log(`  ${ok ? 'ok  ' : 'FAIL'} ${what}`); if (!ok) bad++; }
console.log(bad ? `\n${bad} check(s) FAILED` : '\nall checks pass');
process.exit(bad ? 1 : 0);
