#!/usr/bin/env node
/**
 * wire_asset_packs.js — put the eleven asset-pack modules into the Gradle build.
 *
 *   node scripts/wire_asset_packs.js <native-repo> <packs-dir>
 *
 * Idempotent, exact-count guards, and it commits the WIRING only — never the 742 MB of assets.
 *
 * WHAT IS COMMITTED AND WHAT IS NOT, which is the whole design here:
 *
 *   committed    android/rc-<id>/build.gradle          11 files, ~600 bytes each
 *                android/settings.gradle               11 include lines
 *                android/app/build.gradle              one assetPacks line
 *                .gitignore                            the packs' src directories
 *
 *   generated    android/rc-<id>/src/main/assets/...   742 MB, from the web repo
 *
 * The assets are a build artifact of `rounds-codex-app`, exactly like `www/`. Committing them
 * would make every clone unusable and they would go stale the next time the app ships. The
 * physician regenerates them with `build_asset_packs.js --copy` before a release build, and
 * `verify_asset_packs.js` proves base + packs covers everything the app can request.
 *
 * WHY install-time PACKS AND NOT on-demand: on-demand needs the Play Core API called from Java,
 * which means a native plugin. Install-time packs ship as split APKs and are simply present, so
 * the offline claim in the listing holds from first launch and no Java is written at all. See
 * HANDOFF-android-app.md §4.3 -- whether Capacitor's WebViewLocalServer can READ them is still the
 * open question, and only an emulator settles it.
 *
 * DO NOT RENAME A PACK after it has shipped: to Play a renamed pack is a new pack, and every
 * device re-downloads it.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const REPO = process.argv[2], PACKS = process.argv[3];
if (!REPO || !PACKS) {
  console.error('usage: wire_asset_packs.js <native-repo> <packs-dir>');
  process.exit(2);
}

const ids = fs.readdirSync(PACKS)
  .filter(d => fs.statSync(path.join(PACKS, d)).isDirectory())
  .filter(d => fs.existsSync(path.join(PACKS, d, 'build.gradle')))
  .sort();
if (!ids.length) { console.error(`FAIL: no pack modules in ${PACKS}`); process.exit(1); }

/* ---- 1. the module build.gradle files -------------------------------------------------- */
for (const id of ids) {
  const dst = path.join(REPO, 'android', id);
  fs.mkdirSync(dst, { recursive: true });
  fs.copyFileSync(path.join(PACKS, id, 'build.gradle'), path.join(dst, 'build.gradle'));
}
console.log(`  ok  ${ids.length} pack module build.gradle file(s) written`);

/* ---- 2. settings.gradle ---------------------------------------------------------------- */
const SETTINGS = path.join(REPO, 'android', 'settings.gradle');
let set = fs.readFileSync(SETTINGS, 'utf8');
const MARK = '// --- Play Asset Delivery: generated by scripts/wire_asset_packs.js ---';
if (set.includes(MARK)) {
  console.log('  --  settings.gradle already wired');
} else {
  const block = '\n\n' + MARK + '\n' + ids.map(i => `include ':${i}'`).join('\n') + '\n';
  set = set.replace(/\s*$/, '') + block;
  fs.writeFileSync(SETTINGS, set);
  console.log(`  ok  settings.gradle: ${ids.length} include line(s)`);
}

/* ---- 3. app/build.gradle --------------------------------------------------------------- */
const APPGRADLE = path.join(REPO, 'android', 'app', 'build.gradle');
let app = fs.readFileSync(APPGRADLE, 'utf8');
const LINE = `    assetPacks = [${ids.map(i => `":${i}"`).join(', ')}]`;
if (/^\s*assetPacks\s*=/m.test(app)) {
  /* Re-wiring after the pack set changed: replace the line rather than adding a second. */
  app = app.replace(/^\s*assetPacks\s*=.*$/m, LINE);
  console.log('  ok  app/build.gradle: assetPacks line updated');
} else {
  const ANCHOR = '    compileSdk = rootProject.ext.compileSdkVersion\n';
  const n = app.split(ANCHOR).length - 1;
  if (n !== 1) {
    console.error(`FAIL: compileSdk anchor found ${n} time(s) in app/build.gradle, expected 1`);
    process.exit(1);
  }
  app = app.replace(ANCHOR, ANCHOR + LINE + '\n');
  console.log(`  ok  app/build.gradle: assetPacks = [${ids.length} pack(s)]`);
}
fs.writeFileSync(APPGRADLE, app);

/* ---- 4. keep the 742 MB out of git ----------------------------------------------------- */
const GI = path.join(REPO, '.gitignore');
let gi = fs.readFileSync(GI, 'utf8');
const IGNORE = 'android/rc-*/src/';
if (gi.split('\n').some(l => l.trim() === IGNORE)) {
  console.log('  --  .gitignore already excludes the pack assets');
} else {
  gi = gi.replace(/^www\/$/m, 'www/\n' + IGNORE);
  fs.writeFileSync(GI, gi);
  console.log(`  ok  .gitignore: ${IGNORE}  (the assets are a build artifact, like www/)`);
}

/* ---- assert ---------------------------------------------------------------------------- */
const s2 = fs.readFileSync(SETTINGS, 'utf8'), a2 = fs.readFileSync(APPGRADLE, 'utf8');
const g2 = fs.readFileSync(GI, 'utf8');
const checks = [
  [`settings.gradle includes all ${ids.length}`, ids.every(i => s2.includes(`include ':${i}'`))],
  ['settings.gradle keeps :app and the cordova plugins module',
    s2.includes("include ':app'") && s2.includes("include ':capacitor-cordova-android-plugins'")],
  ['settings.gradle still applies capacitor.settings.gradle',
    s2.includes("apply from: 'capacitor.settings.gradle'")],
  ['exactly one assetPacks line', (a2.match(/^\s*assetPacks\s*=/gm) || []).length === 1],
  [`assetPacks names all ${ids.length}`, ids.every(i => a2.includes(`":${i}"`))],
  ['assetPacks is inside the android block',
    a2.indexOf('assetPacks') > a2.indexOf('android {') &&
    a2.indexOf('assetPacks') < a2.indexOf('defaultConfig')],
  ['pack assets are gitignored', g2.includes(IGNORE)],
  ['every module has its build.gradle',
    ids.every(i => fs.existsSync(path.join(REPO, 'android', i, 'build.gradle')))],
  ['every pack is install-time', ids.every(i =>
    fs.readFileSync(path.join(REPO, 'android', i, 'build.gradle'), 'utf8')
      .includes('deliveryType = "install-time"'))],
];
let bad = 0;
console.log('');
for (const [what, ok] of checks) { console.log(`  ${ok ? 'ok  ' : 'FAIL'} ${what}`); if (!ok) bad++; }
console.log(bad ? `\n${bad} check(s) FAILED` : `\nall checks pass — ${ids.length} install-time packs wired`);
process.exit(bad ? 1 : 0);
