#!/usr/bin/env python3
"""Generate tools/download-rounds-codex-images.command from generated-image-urls.json.

    python3 tools/build_download_command.py

The script it writes names every file by its exam question id, so the mapping travels with
the filenames rather than living only in this repo. No login is needed: the CloudFront URLs
are public objects (see HARVEST-HANDOFF.md -- a 403 from this container is the agent proxy
refusing CONNECT, not CloudFront refusing the request).

THE RESUME GUARD IS A TRAP FOR RE-FIRES, which is why this generator exists.

The script skips any file already on disk, so a partial download resumes instead of
re-fetching 190 images. But when a prompt is corrected and re-fired, the id keeps its
filename while the URL changes -- so a laptop that already downloaded the old, WRONG image
would skip it and silently keep it. The wrong images are the whole reason for the re-fire
and they look completely fine, so nothing downstream would catch it.

Fix: any id whose URL differs from the one in superseded-image-urls.json gets deleted at the
top of the script before the download loop runs. A machine that never downloaded the old copy
is unaffected; one that did gets it replaced.
"""
import json, os, io

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DONE = os.path.join(ROOT, 'tools', 'generated-image-urls.json')
OLD = os.path.join(ROOT, 'tools', 'superseded-image-urls.json')
OUT = os.path.join(ROOT, 'tools', 'download-rounds-codex-images.command')

urls = json.load(open(DONE))
superseded = json.load(open(OLD)) if os.path.exists(OLD) else {}
# only ids whose URL actually moved -- an unchanged entry must not be force-deleted
stale = sorted(i for i, u in superseded.items() if i in urls and urls[i] != u)

n = len(urls)
L = []
L.append('#!/bin/bash')
L.append(f'# Downloads all {n} Rounds Codex illustrations, named by the exam question they belong to.')
L.append('# Double-click this file on a Mac. On Windows/Linux run:  bash download-rounds-codex-images.command')
L.append('#')
L.append('# No Higgsfield login is needed -- the image URLs are plain public CloudFront links.')
L.append('# Files land in a folder called rounds-codex-images next to this script.')
L.append('#')
L.append('# Generated by tools/build_download_command.py -- do not hand-edit.')
L.append('')
L.append('cd "$(dirname "$0")" || exit 1')
L.append('mkdir -p rounds-codex-images && cd rounds-codex-images || exit 1')
L.append(f'echo "Downloading {n} images into $(pwd)"')

if stale:
    L.append('')
    L.append('# These prompts were corrected and re-fired, so the id keeps its filename while the')
    L.append('# image behind it changed. Delete any stale copy first -- the skip-if-present guard')
    L.append('# below would otherwise keep the old, wrong image forever.')
    L.append('replaced=0')
    for i in stale:
        L.append(f'if [ -f "{i}.png" ]; then rm -f "{i}.png"; replaced=$((replaced+1)); fi')
    L.append(f'if [ "$replaced" -gt 0 ]; then echo "Replacing $replaced superseded image(s) of {len(stale)} re-fired"; fi')

L.append('')
L.append('ok=0; fail=0; skip=0')
L.append('')
for i in sorted(urls):
    u = urls[i]
    L.append(f'if [ -s "{i}.png" ]; then skip=$((skip+1)); else')
    L.append(f'  if curl -fsS --retry 3 --retry-delay 2 -o "{i}.png" "{u}"; '
             f'then ok=$((ok+1)); printf "."; else fail=$((fail+1)); printf "X"; rm -f "{i}.png"; fi')
    L.append('fi')

L.append('')
L.append('echo')
L.append('echo "downloaded $ok, already present $skip, failed $fail"')
L.append('if [ "$fail" -gt 0 ]; then echo "Re-run this script to retry the failures."; fi')
L.append('')

io.open(OUT, 'w', encoding='utf-8').write('\n'.join(L))
os.chmod(OUT, 0o755)
print(f'wrote {OUT}')
print(f'  {n} images, {len(stale)} force-replaced: {", ".join(stale) if stale else "none"}')
