#!/usr/bin/env python3
"""
Incorporate approved real/AI images into the USMLE module.

Takes a folder of images named <question-id>.<ext> (e.g. s2ck-0178.png), optimizes
each (downscale + compress), copies them to preview/img/, and writes
preview/illus-real.js which OVERRIDES the schematic SVG for those ids via the
RC_ILLUS registry (loaded last, so it wins). No engine change per image.

MEDICAL-SAFETY DEFAULTS:
  * Only ids present as image files are wired; everything else keeps its schematic.
  * If --decisions is given, only ids in its "approved" list are wired (physician gate).
  * ECG items (isECG in the manifest) are SKIPPED unless --include-ecg — AI cannot
    reliably render correct ECGs; keep those as vector tracings.

Usage:
  python tools/incorporate_images.py --images tools/candidates \
      [--decisions decisions.json] [--include-ecg] [--max-width 720] [--quality 85]

Then rebuild the preview zip.
"""
import argparse, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "tools", "image-manifest.json")
IMG_OUT = os.path.join(ROOT, "preview", "img")
JS_OUT = os.path.join(ROOT, "preview", "illus-real.js")
EXTS = (".png", ".jpg", ".jpeg", ".webp")

def esc_attr(s):
    return (s or "").replace('"', "&quot;")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--images", default=os.path.join(ROOT, "tools", "candidates"))
    ap.add_argument("--decisions", default=None)
    ap.add_argument("--include-ecg", action="store_true")
    ap.add_argument("--max-width", type=int, default=720)
    ap.add_argument("--quality", type=int, default=85)
    a = ap.parse_args()

    from PIL import Image  # Pillow

    man = json.load(open(MANIFEST))
    by_id = {it["id"]: it for it in man["items"]}
    total_illus = len(by_id)

    approved = None
    if a.decisions and os.path.exists(a.decisions):
        d = json.load(open(a.decisions))
        approved = set(d.get("approved", []))
        print(f"decisions: {len(approved)} approved ids (physician gate ON)")

    os.makedirs(IMG_OUT, exist_ok=True)
    wired, skipped_ecg, skipped_unapproved, entries = [], [], [], []

    for qid, it in by_id.items():
        src = next((os.path.join(a.images, qid + e) for e in EXTS
                    if os.path.exists(os.path.join(a.images, qid + e))), None)
        if not src:
            continue
        if it.get("isECG") and not a.include_ecg:
            skipped_ecg.append(qid); continue
        if approved is not None and qid not in approved:
            skipped_unapproved.append(qid); continue

        im = Image.open(src).convert("RGB")
        if im.width > a.max_width:
            h = round(im.height * a.max_width / im.width)
            im = im.resize((a.max_width, h), Image.LANCZOS)
        dst = os.path.join(IMG_OUT, qid + ".jpg")
        im.save(dst, "JPEG", quality=a.quality, optimize=True)
        alt = esc_attr((it.get("title") or qid))
        entries.append("  '%s': '<img src=\"img/%s.jpg\" alt=\"%s\" loading=\"lazy\">'" % (qid, qid, alt))
        wired.append(qid)

    header = ("// preview/illus-real.js — real/AI images that OVERRIDE schematic SVGs.\n"
              "// Generated by tools/incorporate_images.py. Loaded LAST so RC_ILLUS[id] here wins.\n"
              "// Each image is physician-reviewed; ECGs stay vector unless --include-ecg.\n")
    body = "Object.assign(window.RC_ILLUS = window.RC_ILLUS || {}, {\n" + ",\n".join(entries) + ("\n" if entries else "") + "});\n"
    open(JS_OUT, "w").write(header + body)

    print(f"\nwired {len(wired)} real images -> preview/img/ + preview/illus-real.js")
    print(f"coverage: {len(wired)}/{total_illus} illustrated items now use real images "
          f"({total_illus-len(wired)} keep schematics)")
    if skipped_ecg:
        print(f"skipped {len(skipped_ecg)} ECG items (kept vector; pass --include-ecg to override)")
    if skipped_unapproved:
        print(f"skipped {len(skipped_unapproved)} not in the approved decisions list")
    if not entries:
        print("(no images found — illus-real.js is an empty stub; nothing overridden)")

if __name__ == "__main__":
    main()
